/**
 * The artifact is the same sheet the proof runs, plus a React wrapper that
 * applies data-state and data-edge the way the desk does. Paste both files.
 * If onChange returns a promise, the pending journey is used until it settles.
 */

import { compileSheet } from "./css";
import { GESTURES, type Doc, type Gesture } from "./model";

export function fileStem(doc: Doc): string {
  return doc.specimen === "switch" ? "StateSwitch" : "StateCommit";
}

export function emitCss(doc: Doc): string {
  return compileSheet(doc, `.${fileStem(doc)}`);
}

function words(doc: Doc): string[] {
  return [...new Set(doc.states.map((p) => p.word))];
}

function marks(doc: Doc): string[] {
  return [...new Set(doc.states.map((p) => p.mark))].filter((m) => m !== "none");
}

function edgeLiteral(doc: Doc): string {
  const rows = doc.edges
    .map((e) => {
      const g = e.gesture ? `, gesture: "${e.gesture}"` : "";
      return `  { from: "${e.from}", to: "${e.to}", edge: "${e.id}"${g} }`;
    })
    .join(",\n");
  return `const JOURNEYS = [\n${rows}\n] as const;`;
}

function gestureUnion(doc: Doc): string {
  const set = new Set<string>();
  for (const e of doc.edges) if (e.gesture) set.add(e.gesture);
  const extra = [...set].filter((g) => g !== "click" && g !== "reply");
  return extra.length ? extra.map((g) => `"${g}"`).join(" | ") : "";
}

function commentGestures(doc: Doc): string {
  return doc.edges
    .filter((e) => e.gesture)
    .map((e) => {
      const g = GESTURES.find((x) => x.id === e.gesture);
      return ` *   ${e.from} —${g?.label ?? e.gesture}→ ${e.to}  (${e.duration}ms ${e.easing})`;
    })
    .join("\n");
}

export function emitTsx(doc: Doc): string {
  const name = fileStem(doc);
  const css = `./${name}.css`;
  const labels = words(doc);
  const markList = marks(doc);
  const role = doc.specimen === "switch" ? 'role="switch"' : "";
  const checked =
    doc.specimen === "switch" ? `\n      aria-checked={state === "on"}` : "";
  const start = doc.states[0]?.id ?? "rest";
  const hasPending = doc.states.some((p) => p.id === "pending");
  const extra = gestureUnion(doc);
  const needsPointer =
    extra.includes("enter") || extra.includes("leave") || extra.includes("down") || extra.includes("up");

  const wordSpans = labels
    .map((w) => `        <span data-word="${w}">{${JSON.stringify(w)}}</span>`)
    .join("\n");

  const markSpans = markList
    .map((m) => `      <span className="scMark" data-mark="${m}" aria-hidden="true" />`)
    .join("\n");

  const switchTrack =
    doc.specimen === "switch"
      ? `      <span className="scTrack" aria-hidden="true">
        <span className="scThumb" />
      </span>\n`
      : "";

  const pointerHandlers = needsPointer
    ? `
      onPointerEnter={() => take("enter")}
      onPointerLeave={() => take("leave")}
      onPointerDown={() => { pointer.current = true; take("down"); }}
      onPointerUp={() => take("up")}`
    : "";

  const pointerImport = needsPointer ? ", useRef" : "";
  const pointerRef = needsPointer ? `  const pointer = useRef(false);\n` : "";
  const clickGuard = needsPointer
    ? `    if (pointer.current) {
      pointer.current = false;
      return;
    }
`
    : "";

  const nextArg =
    doc.specimen === "switch" ? `state === "on" ? "off" : "on"` : `"done"`;

  return `"use client";

/**
 * Generated by Statecraft. The sheet is the choreography; this file only
 * chooses which journey to take.
 *
 * Gestures:
${commentGestures(doc)}
 *
 * Pass onChange if the control must wait. A returned promise holds the
 * pending station until it settles; a thrown error walks back.
 */
import { useState${pointerImport} } from "react";
import "${css}";

type State = ${doc.states.map((p) => JSON.stringify(p.id)).join(" | ")};
type Gesture = "click" | "reply"${extra ? ` | ${extra}` : ""};

${edgeLiteral(doc)}

function findGesture(from: State, gesture: Gesture) {
  return JOURNEYS.find((j) => j.from === from && "gesture" in j && j.gesture === gesture);
}

function findTo(from: State, to: State) {
  return JOURNEYS.find((j) => j.from === from && j.to === to);
}

export function ${name}({
  defaultState = ${JSON.stringify(start)},
  onChange,
}: {
  defaultState?: State;
  onChange?: (next: State) => Promise<void> | void;
}) {
  const [state, setState] = useState<State>(defaultState);
  const [edge, setEdge] = useState(${JSON.stringify(doc.edges[0]?.id ?? "")});
${pointerRef}${hasPending ? `  const busy = state === "pending";\n` : ""}
  function apply(next: State, edgeId: string) {
    setEdge(edgeId);
    setState(next);
  }

  function take(gesture: Gesture) {
    const j = findGesture(state, gesture);
    if (!j) return;
    apply(j.to as State, j.edge);
  }

  async function onClick() {
${clickGuard}    const click = findGesture(state, "click");
    const up = findGesture(state, "up");
    const skip = findTo(state, "pending" as State);
    const j = click ?? up ?? skip;
    if (!j) return;
    if (onChange && j.to === "pending") {
      apply("pending", j.edge);
      try {
        await onChange(${nextArg});
        const reply = findGesture("pending" as State, "reply");
        if (reply) apply(reply.to as State, reply.edge);
      } catch {
        const back = JOURNEYS.find((x) => x.from === "pending" && x.to === state);
        if (back) apply(state, back.edge);
        else apply(state, j.edge);
      }
      return;
    }
    apply(j.to as State, j.edge);
  }

  return (
    <button
      type="button"
      ${role}${checked}
      aria-busy={${hasPending ? "busy" : "false"}}
      className="${name}"
      data-state={state}
      data-edge={edge}
      onClick={onClick}${pointerHandlers}
      disabled={${hasPending ? "busy" : "false"}}
    >
${switchTrack}      <span className="scWord">
${wordSpans}
      </span>
${markSpans}
    </button>
  );
}
`;
}

export function emitDocument(doc: Doc): { tsx: string; css: string; stem: string } {
  return { tsx: emitTsx(doc), css: emitCss(doc), stem: fileStem(doc) };
}

export function gestureLabel(g: Gesture | undefined): string {
  if (!g) return "graph only";
  return GESTURES.find((x) => x.id === g)?.label ?? g;
}
