/**
 * The artifact is a module that runs without this bench. Same integrator,
 * same detent hill, same three-voice click. Paste it onto a real control.
 */

import {
  busyNeed,
  holdNeed,
  matchPreset,
  travelPx,
  type Recipe,
} from "./feel";

export function fileStem(recipe: Recipe): string {
  const preset = matchPreset(recipe);
  return `actuator-${preset ? preset.id : "custom"}`;
}

export function emitRecipe(recipe: Recipe): string {
  const keys = Object.keys(recipe) as (keyof Recipe)[];
  const body = keys
    .map((k) => `  ${k}: ${Number(recipe[k].toFixed(4))}`)
    .join(",\n");
  return `{\n${body}\n}`;
}

export function emitModule(recipe: Recipe): string {
  const preset = matchPreset(recipe);
  const name = preset ? preset.name : "Custom";
  const px = travelPx(recipe.travel);
  const hold = holdNeed(recipe).toFixed(3);
  const busy = busyNeed(recipe).toFixed(3);

  return `/**
 * Actuator feel — ${name}
 * Generated by Actuator. Same spring, same click as the bench.
 *
 * <button class="act">Send</button>
 * <script type="module">
 *   import { attach, feel } from "./${fileStem(recipe)}.js";
 *   attach(document.querySelector(".act"), {
 *     feel,
 *     onCommit() { console.log("fired"); },
 *   });
 * </script>
 *
 * The button should have position: relative and a child .act-cap,
 * or attach() will translate the button itself by --act-x.
 */
export const feel = ${emitRecipe(recipe)};

export function attach(el, options = {}) {
  const recipe = { ...feel, ...(options.feel || {}) };
  const role = options.role || "momentary";
  const onCommit = options.onCommit || (() => {});
  const muted = !!options.muted;
  const travel = ${px};
  const holdNeed = ${hold};
  const busyNeed = ${busy};
  const reduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches;

  const k = 28 * recipe.stiffness;
  const m = 0.12 * recipe.mass;
  const c = 2 * recipe.damping * Math.sqrt(k * m);
  const preloadF = recipe.preload * k * 0.38;

  const body = { x: 0, v: 0, latched: false, hold: 0, busyLeft: 0, stroke: false, fired: false };
  let held = false;
  let depth = 1;
  let originY = 0;
  let moved = false;
  let ballistic = 0;
  let ctx = null;
  let noise = null;
  let raf = 0;
  let acc = 0;
  let last = performance.now();
  let lastPtr = 0;

  function detent(x) {
    if (recipe.detent < 0.01) return 0;
    const d = x - recipe.commit;
    const w = 0.055;
    return recipe.detent * k * 0.2 * (d / (w * w)) * Math.exp(-(d * d) / (2 * w * w));
  }

  function unlock() {
    if (!ctx) {
      const Ctor = window.AudioContext || window.webkitAudioContext;
      if (!Ctor) return;
      ctx = new Ctor();
      noise = ctx.createBuffer(1, Math.floor(ctx.sampleRate * 0.014), ctx.sampleRate);
      const data = noise.getChannelData(0);
      for (let i = 0; i < data.length; i++) {
        data[i] = (Math.random() * 2 - 1) * Math.exp(-i / (data.length * 0.2));
      }
    }
    if (ctx.state === "suspended") ctx.resume();
  }

  function click(velocity) {
    if (muted || !ctx || ctx.state !== "running") return;
    const t = ctx.currentTime;
    const v = Math.min(1, 0.22 + velocity * 0.55);
    const gain = 0.2 * v;
    const dest = ctx.destination;

    const tick = ctx.createBufferSource();
    tick.buffer = noise;
    const hp = ctx.createBiquadFilter();
    hp.type = "highpass";
    hp.frequency.value = 700 + recipe.hardness * 2600;
    const tg = ctx.createGain();
    tg.gain.setValueAtTime(Math.max(0.0001, gain * recipe.hardness), t);
    tg.gain.exponentialRampToValueAtTime(0.0001, t + 0.016);
    tick.connect(hp).connect(tg).connect(dest);
    tick.start(t);

    const osc = ctx.createOscillator();
    osc.type = "triangle";
    osc.frequency.setValueAtTime(recipe.pitch, t);
    osc.frequency.exponentialRampToValueAtTime(Math.max(40, recipe.pitch * 0.7), t + recipe.body);
    const bg = ctx.createGain();
    bg.gain.setValueAtTime(Math.max(0.0001, gain * (0.32 + (1 - recipe.hardness) * 0.45)), t);
    bg.gain.exponentialRampToValueAtTime(0.0001, t + recipe.body);
    osc.connect(bg).connect(dest);
    osc.start(t);
    osc.stop(t + recipe.body + 0.03);

    const partial = ctx.createOscillator();
    partial.type = "sine";
    partial.frequency.value = recipe.pitch * 2.35;
    const pg = ctx.createGain();
    pg.gain.setValueAtTime(Math.max(0.0001, gain * 0.16 * recipe.hardness), t);
    pg.gain.exponentialRampToValueAtTime(0.0001, t + recipe.body * 0.48);
    partial.connect(pg).connect(dest);
    partial.start(t);
    partial.stop(t + recipe.body * 0.55 + 0.01);
  }

  function target() {
    if (el.disabled) return 0;
    if (role === "busy" && body.busyLeft > 0) return body.busyLeft > 0.28 ? 0.86 : 0;
    const pulled = held || ballistic > 0;
    if (role === "latch" && body.latched) return held ? 0.78 + depth * 0.22 : 0.78;
    if (!pulled) return 0;
    return held ? depth : 1;
  }

  function paint() {
    const x = Math.max(0, body.x);
    el.style.setProperty("--act-x", x.toFixed(4));
    const cap = el.querySelector(".act-cap");
    const node = cap || el;
    node.style.transform = "translateY(" + (x * travel) + "px)";
  }

  function step(dt) {
    if (el.disabled) {
      body.x = 0;
      body.v = 0;
      return;
    }
    if (ballistic > 0) {
      ballistic = Math.max(0, ballistic - dt);
      if (body.stroke) ballistic = 0;
      else if (!body.latched && body.x >= recipe.commit) ballistic = 0;
    }
    if (body.busyLeft > 0) body.busyLeft = Math.max(0, body.busyLeft - dt);

    const tgt = target();
    const prev = body.x;

    if (reduced) {
      body.x = tgt;
      body.v = 0;
    } else {
      let F = -k * (body.x - tgt) - c * body.v + detent(body.x);
      const pulled = held || ballistic > 0;
      if (!pulled && body.x < 0.018 && Math.abs(body.v) < 0.08 && !body.latched) {
        body.x = 0;
        body.v = 0;
        F = 0;
      } else if (pulled && body.x < 0.02 && F > 0 && F < preloadF && !body.latched) {
        F = 0;
        body.v = 0;
      }
      body.v += (F / m) * dt;
      body.x += body.v * dt;
      if (body.x > 1.08) { body.x = 1.08; body.v *= -0.12; }
      if (body.x < -0.04) { body.x = -0.04; body.v *= -0.08; }
    }

    const rising = body.x >= recipe.commit && prev < recipe.commit;
    let fired = false;
    let vel = Math.max(0.15, Math.abs(body.v));

    if (role === "latch" && body.latched) {
      if ((held || ballistic > 0) && body.x >= 0.94 && !body.stroke) {
        body.latched = false;
        body.stroke = true;
        el.setAttribute("aria-pressed", "false");
        click(vel);
      }
      if (!held && ballistic === 0) body.stroke = false;
      return;
    }

    if (rising && !body.stroke) {
      body.stroke = true;
      click(vel);
      if (role === "momentary" || role === "busy") {
        fired = true;
        if (role === "busy") {
          body.busyLeft = busyNeed;
          el.setAttribute("aria-busy", "true");
        }
      } else if (role === "latch") {
        body.latched = true;
        fired = true;
        el.setAttribute("aria-pressed", "true");
      }
    }

    if (role === "hold") {
      if (held && body.x >= recipe.commit) {
        body.hold += dt;
        if (!body.fired && body.hold >= holdNeed) {
          fired = true;
          body.fired = true;
          click(vel);
        }
      } else if (!held) {
        body.hold = 0;
      }
    }

    if (fired) onCommit();
    if (role === "busy" && body.busyLeft === 0) el.removeAttribute("aria-busy");

    if (!held && ballistic === 0 && body.x < recipe.commit * 0.55) {
      body.stroke = false;
      body.fired = false;
      if (role === "hold") body.hold = 0;
    }
  }

  function frame(now) {
    const dt = Math.min(0.048, (now - last) / 1000);
    last = now;
    acc += dt;
    const tick = 1 / 120;
    while (acc >= tick) {
      step(tick);
      acc -= tick;
    }
    paint();
    raf = requestAnimationFrame(frame);
  }

  function down(e) {
    if (el.disabled || (role === "busy" && body.busyLeft > 0)) return;
    lastPtr = performance.now();
    unlock();
    held = true;
    moved = false;
    ballistic = 0;
    originY = e.clientY;
    depth = 1;
    if (e.pointerId != null) el.setPointerCapture(e.pointerId);
    e.preventDefault();
  }

  function move(e) {
    if (!held) return;
    const dy = e.clientY - originY;
    if (dy > 12) {
      moved = true;
      depth = Math.min(1, Math.max(0, dy / travel));
    }
  }

  function up() {
    held = false;
    depth = 1;
    if (role !== "hold" && !moved && !body.stroke) ballistic = 0.55;
  }

  function keydown(e) {
    if (e.code !== "Space" && e.code !== "Enter") return;
    if (e.repeat) return;
    e.preventDefault();
    unlock();
    held = true;
    depth = 1;
  }

  function keyup(e) {
    if (e.code !== "Space" && e.code !== "Enter") return;
    e.preventDefault();
    held = false;
  }

  function onClick() {
    if (performance.now() - lastPtr < 500) return;
    unlock();
    held = true;
    depth = 1;
    moved = false;
    held = false;
    if (role !== "hold" && !body.stroke) ballistic = 0.55;
  }

  el.style.touchAction = "none";
  el.addEventListener("pointerdown", down);
  el.addEventListener("pointermove", move);
  el.addEventListener("pointerup", up);
  el.addEventListener("pointercancel", up);
  el.addEventListener("click", onClick);
  el.addEventListener("keydown", keydown);
  el.addEventListener("keyup", keyup);
  raf = requestAnimationFrame(frame);

  return {
    destroy() {
      cancelAnimationFrame(raf);
      el.removeEventListener("pointerdown", down);
      el.removeEventListener("pointermove", move);
      el.removeEventListener("pointerup", up);
      el.removeEventListener("pointercancel", up);
      el.removeEventListener("click", onClick);
      el.removeEventListener("keydown", keydown);
      el.removeEventListener("keyup", keyup);
    },
  };
}
`;
}

export function emitPreview(recipe: Recipe): string {
  const full = emitModule(recipe);
  const lines = full.split("\n");
  return lines.slice(0, 22).join("\n");
}
