import type { Production } from "./types";

/**
 * Modelled mid-scale get-in, frozen on Monday 31 August 2026.
 *
 * The house, the play, the people and every date are invented. The shape is
 * not: previous get-out, hired desk on a locked day, a 21-day mill, a licence
 * she does not control, and an opening night with tickets already sold.
 * Standing daily jobs (sweep, laundry, the call) are left off; this is the
 * extract a production manager keeps because it has a dependency or a lead.
 */
export const PRODUCTION: Production = {
  title: "The Salt Line",
  writer: "Nia Caradoc",
  venue: "Borough Playhouse",
  today: "2026-08-31",
  opening: "2026-10-02",
  already: {
    "set-drawings": "2026-08-10",
    "set-steel": "2026-08-18",
    "set-flats": "2026-08-28",
    "lx-design": "2026-08-14",
    "lx-hire": "2026-08-15",
    "snd-design": "2026-08-20",
    "cos-design": "2026-08-08",
    "props-list": "2026-08-12",
    "cast-room": "2026-08-31",
  },
  tasks: [
    // —— Set ———————————————————————————————————————————————————————————
    {
      id: "set-drawings",
      name: "Construction drawings signed",
      dept: "set",
      owner: "Jed Hollis",
      days: 0,
      wait: 0,
      depends: [],
      kind: "work",
    },
    {
      id: "set-steel",
      name: "Order hired steel deck",
      dept: "set",
      owner: "Jed Hollis",
      days: 1,
      wait: 10,
      depends: ["set-drawings"],
      kind: "lead",
      external: true,
      note: "Deck is coming from a hire house. Ten calendar days from the order.",
    },
    {
      id: "set-flats",
      name: "Build Act 1 flats in the workshop",
      dept: "set",
      owner: "Jed Hollis",
      days: 8,
      wait: 0,
      depends: ["set-drawings"],
      kind: "work",
    },
    {
      id: "set-truck",
      name: "Finish the kitchen truck",
      dept: "set",
      owner: "Jed Hollis",
      days: 9,
      wait: 0,
      depends: ["set-drawings"],
      kind: "work",
      note: "Nine days of workshop time still on it. Paint cannot start until it is in the paint frame.",
    },
    {
      id: "set-paint",
      name: "Paint workshop pieces",
      dept: "set",
      owner: "Jed Hollis",
      days: 5,
      wait: 0,
      depends: ["set-flats", "set-truck"],
      kind: "work",
      note: "Must be dry before the load-in on the 14th. The truck is what is eating the air.",
    },
    {
      id: "set-getout",
      name: "Wintering get-out",
      dept: "set",
      owner: "Venue",
      days: 1,
      wait: 0,
      depends: [],
      kind: "gate",
      on: "2026-09-13",
      gate: "2026-09-13",
      external: true,
      note: "The previous production. The stage is not ours until this is finished.",
    },
    {
      id: "set-loadin",
      name: "Load-in to the theatre",
      dept: "set",
      owner: "Jed Hollis",
      days: 1,
      wait: 0,
      depends: ["set-paint", "set-steel", "set-getout"],
      kind: "work",
    },
    {
      id: "set-build",
      name: "Build the set on stage",
      dept: "set",
      owner: "Jed Hollis",
      days: 3,
      wait: 0,
      depends: ["set-loadin"],
      kind: "work",
    },
    {
      id: "set-safe",
      name: "Sign the set safe for the company",
      dept: "set",
      owner: "Iona Vale",
      days: 1,
      wait: 0,
      depends: ["set-build"],
      kind: "work",
      note: "Nobody from the company walks it until Iona has signed.",
    },
    {
      id: "set-masking",
      name: "Hang masking and blacks",
      dept: "set",
      owner: "Jed Hollis",
      days: 2,
      wait: 0,
      depends: ["set-build"],
      kind: "work",
    },

    // —— Lighting ——————————————————————————————————————————————————————
    {
      id: "lx-design",
      name: "Lighting design locked",
      dept: "lx",
      owner: "Sol Okonkwo",
      days: 0,
      wait: 0,
      depends: [],
      kind: "work",
    },
    {
      id: "lx-hire",
      name: "Submit the lighting hire",
      dept: "lx",
      owner: "Sol Okonkwo",
      days: 1,
      wait: 7,
      depends: ["lx-design"],
      kind: "lead",
      external: true,
    },
    {
      id: "lx-desk",
      name: "Hired lighting desk arrives",
      dept: "lx",
      owner: "Hire house",
      days: 0,
      wait: 0,
      depends: [],
      kind: "gate",
      gate: "2026-09-16",
      on: "2026-09-16",
      external: true,
      note: "The desk is booked for the 16th. Nothing can be patched or plotted in the room before it is on the desk.",
    },
    {
      id: "lx-specials",
      name: "Order haze and the followspot",
      dept: "lx",
      owner: "Sol Okonkwo",
      days: 1,
      wait: 5,
      depends: ["lx-design"],
      kind: "lead",
      external: true,
      note: "Five-day hire notice. Needed on the floor before the rig.",
    },
    {
      id: "lx-rig",
      name: "Rig the lighting",
      dept: "lx",
      owner: "Sol Okonkwo",
      days: 2,
      wait: 0,
      depends: ["set-build", "lx-hire", "lx-specials"],
      kind: "work",
      note: "Cannot go up until the set is in. The specials have to be in the building.",
    },
    {
      id: "lx-patch",
      name: "Patch",
      dept: "lx",
      owner: "Sol Okonkwo",
      days: 1,
      wait: 0,
      depends: ["lx-rig", "lx-desk"],
      kind: "work",
    },
    {
      id: "lx-focus",
      name: "Focus",
      dept: "lx",
      owner: "Sol Okonkwo",
      days: 2,
      wait: 0,
      depends: ["lx-patch"],
      kind: "work",
    },
    {
      id: "lx-plot",
      name: "Plotting session",
      dept: "lx",
      owner: "Sol Okonkwo",
      days: 1,
      wait: 0,
      depends: ["lx-focus"],
      kind: "work",
    },

    // —— Sound —————————————————————————————————————————————————————————
    {
      id: "snd-design",
      name: "Sound design draft",
      dept: "sound",
      owner: "Priya Shah",
      days: 0,
      wait: 0,
      depends: [],
      kind: "work",
    },
    {
      id: "snd-mics",
      name: "Order the radio mics",
      dept: "sound",
      owner: "Priya Shah",
      days: 1,
      wait: 7,
      depends: ["snd-design"],
      kind: "lead",
      external: true,
    },
    {
      id: "snd-rig",
      name: "Rig the speakers",
      dept: "sound",
      owner: "Priya Shah",
      days: 1,
      wait: 0,
      depends: ["set-build", "snd-mics"],
      kind: "work",
    },
    {
      id: "snd-room",
      name: "Hear the room",
      dept: "sound",
      owner: "Priya Shah",
      days: 1,
      wait: 0,
      depends: ["snd-rig", "set-build"],
      kind: "work",
      note: "Priya will not lock the design until she has heard it in this room. That is not stubbornness. It is the work.",
    },
    {
      id: "snd-final",
      name: "Finalise the sound design",
      dept: "sound",
      owner: "Priya Shah",
      days: 3,
      wait: 0,
      depends: ["snd-room"],
      kind: "work",
    },
    {
      id: "snd-qlab",
      name: "Programme QLab",
      dept: "sound",
      owner: "Priya Shah",
      days: 1,
      wait: 0,
      depends: ["snd-final"],
      kind: "work",
    },

    // —— Costume ———————————————————————————————————————————————————————
    {
      id: "cos-design",
      name: "Costume designs approved",
      dept: "costume",
      owner: "Anwen Price",
      days: 0,
      wait: 0,
      depends: [],
      kind: "work",
    },
    {
      id: "cos-silk",
      name: "Order the Act 2 silk",
      dept: "costume",
      owner: "Anwen Price",
      days: 0,
      wait: 21,
      depends: ["cos-design"],
      kind: "lead",
      external: true,
      note: "The mill quotes twenty-one calendar days. There is no faster dye lot in this colour.",
    },
    {
      id: "cos-wool",
      name: "Order the chorus wool",
      dept: "costume",
      owner: "Anwen Price",
      days: 1,
      wait: 14,
      depends: ["cos-design"],
      kind: "lead",
      external: true,
    },
    {
      id: "cos-coats",
      name: "Confirm the period coat hire",
      dept: "costume",
      owner: "Anwen Price",
      days: 1,
      wait: 10,
      depends: ["cos-design"],
      kind: "lead",
      external: true,
    },
    {
      id: "cos-wigs",
      name: "Confirm the wig hire",
      dept: "costume",
      owner: "Anwen Price",
      days: 1,
      wait: 14,
      depends: ["cos-design"],
      kind: "lead",
      external: true,
    },
    {
      id: "cos-shoes",
      name: "Order the character shoes",
      dept: "costume",
      owner: "Anwen Price",
      days: 1,
      wait: 10,
      depends: ["cos-design"],
      kind: "lead",
      external: true,
    },
    {
      id: "cos-make-act2",
      name: "Make the Act 2 dresses",
      dept: "costume",
      owner: "Anwen Price",
      days: 6,
      wait: 0,
      depends: ["cos-silk"],
      kind: "work",
    },
    {
      id: "cos-make-chorus",
      name: "Make the chorus",
      dept: "costume",
      owner: "Anwen Price",
      days: 5,
      wait: 0,
      depends: ["cos-wool"],
      kind: "work",
    },
    {
      id: "cos-alter",
      name: "Alter the hired coats",
      dept: "costume",
      owner: "Anwen Price",
      days: 2,
      wait: 0,
      depends: ["cos-coats"],
      kind: "work",
    },
    {
      id: "cos-fit1",
      name: "First fittings — principals",
      dept: "costume",
      owner: "Anwen Price",
      days: 1,
      wait: 0,
      depends: ["cos-make-act2"],
      kind: "work",
    },
    {
      id: "cos-fit2",
      name: "Second fittings",
      dept: "costume",
      owner: "Anwen Price",
      days: 1,
      wait: 0,
      depends: ["cos-fit1", "cos-alter"],
      kind: "work",
    },
    {
      id: "cos-under",
      name: "Build the understudy costumes",
      dept: "costume",
      owner: "Anwen Price",
      days: 3,
      wait: 0,
      depends: ["cos-make-act2", "cos-make-chorus"],
      kind: "work",
    },
    {
      id: "cos-ready",
      name: "Costumes complete for the first preview",
      dept: "costume",
      owner: "Anwen Price",
      days: 0,
      wait: 0,
      depends: ["cos-fit2", "cos-shoes", "cos-wigs"],
      kind: "work",
    },
    {
      id: "cos-quick",
      name: "Quick-change plot with the DSM",
      dept: "costume",
      owner: "Tom Reeve",
      days: 1,
      wait: 0,
      depends: ["cos-ready"],
      kind: "work",
    },

    // —— Props —————————————————————————————————————————————————————————
    {
      id: "props-list",
      name: "Props list locked",
      dept: "props",
      owner: "Kit Brennan",
      days: 0,
      wait: 0,
      depends: [],
      kind: "work",
    },
    {
      id: "props-pistol",
      name: "Apply for the starter-pistol licence",
      dept: "props",
      owner: "Kit Brennan",
      days: 1,
      wait: 14,
      depends: ["props-list"],
      kind: "lead",
      external: true,
      note: "The police turnaround is fourteen days. Kit cannot accelerate it.",
    },
    {
      id: "props-furniture",
      name: "Hire the Act 1 furniture",
      dept: "props",
      owner: "Kit Brennan",
      days: 1,
      wait: 7,
      depends: ["set-drawings"],
      kind: "lead",
      external: true,
    },
    {
      id: "props-letters",
      name: "Make the letter bundle and photographs",
      dept: "props",
      owner: "Kit Brennan",
      days: 2,
      wait: 0,
      depends: ["props-list"],
      kind: "work",
    },
    {
      id: "props-consumables",
      name: "Order the show consumables",
      dept: "props",
      owner: "Kit Brennan",
      days: 1,
      wait: 5,
      depends: ["props-list"],
      kind: "lead",
      external: true,
    },
    {
      id: "props-dress",
      name: "Dress the set",
      dept: "props",
      owner: "Kit Brennan",
      days: 1,
      wait: 0,
      depends: ["set-safe", "props-furniture", "props-letters", "props-consumables"],
      kind: "work",
    },
    {
      id: "props-weapons",
      name: "Weapons check with the fight director",
      dept: "props",
      owner: "Kit Brennan",
      days: 1,
      wait: 0,
      depends: ["props-pistol", "fight-cert"],
      kind: "work",
    },

    // —— Cast ——————————————————————————————————————————————————————————
    {
      id: "cast-room",
      name: "Rehearse in the room",
      dept: "cast",
      owner: "Ellis Quinn",
      days: 0,
      wait: 0,
      depends: [],
      kind: "work",
      note: "Ongoing in the church hall. Not the constraint.",
    },
    {
      id: "fight-cert",
      name: "Fight-call certification",
      dept: "cast",
      owner: "Iona Vale",
      days: 1,
      wait: 0,
      depends: ["cast-room"],
      kind: "work",
    },
    {
      id: "piano",
      name: "Hire the rehearsal piano",
      dept: "cast",
      owner: "Saffy Rowe",
      days: 1,
      wait: 5,
      depends: [],
      kind: "lead",
      external: true,
    },
    {
      id: "cast-onstage",
      name: "First on-stage rehearsal",
      dept: "cast",
      owner: "Ellis Quinn",
      days: 2,
      wait: 0,
      depends: ["set-safe", "fight-cert"],
      kind: "work",
      note: "The company does not set foot on it until the set is signed safe.",
    },
    {
      id: "sitz",
      name: "Sitzprobe",
      dept: "cast",
      owner: "Priya Shah",
      days: 1,
      wait: 0,
      depends: ["piano", "snd-final"],
      kind: "work",
    },
    {
      id: "tech",
      name: "Technical rehearsal",
      dept: "cast",
      owner: "Iona Vale",
      days: 3,
      wait: 0,
      depends: ["lx-plot", "snd-qlab", "set-safe", "cast-onstage", "props-weapons", "sitz"],
      kind: "event",
      on: "2026-09-24",
      note: "Thursday 24 to Saturday 26 September. The week does not slide.",
    },
    {
      id: "dress",
      name: "Dress rehearsal",
      dept: "cast",
      owner: "Iona Vale",
      days: 1,
      wait: 0,
      depends: ["tech", "cos-make-act2", "cos-make-chorus", "cos-alter", "props-dress"],
      kind: "event",
      on: "2026-09-27",
      note: "Sunday 27 September. Costumes, set dressing, the full picture.",
    },
    {
      id: "preview-1",
      name: "First preview",
      dept: "cast",
      owner: "Saffy Rowe",
      days: 1,
      wait: 0,
      depends: ["dress", "haze-licence", "programme", "house-ready", "cos-ready"],
      kind: "event",
      on: "2026-09-29",
    },
    {
      id: "preview-2",
      name: "Second preview",
      dept: "cast",
      owner: "Saffy Rowe",
      days: 1,
      wait: 0,
      depends: ["preview-1"],
      kind: "event",
      on: "2026-09-30",
    },
    {
      id: "preview-3",
      name: "Third preview",
      dept: "cast",
      owner: "Saffy Rowe",
      days: 1,
      wait: 0,
      depends: ["preview-2"],
      kind: "event",
      on: "2026-10-01",
    },
    {
      id: "opening",
      name: "Press night",
      dept: "cast",
      owner: "Saffy Rowe",
      days: 0,
      wait: 0,
      depends: ["preview-3", "press-seats", "cos-under", "cos-quick"],
      kind: "event",
      on: "2026-10-02",
      note: "Friday 2 October. Tickets are sold. This date does not move.",
    },

    // —— Front of house ————————————————————————————————————————————————
    {
      id: "haze-licence",
      name: "Apply for the haze licence",
      dept: "foh",
      owner: "Mara Chen",
      days: 1,
      wait: 14,
      depends: [],
      kind: "lead",
      external: true,
      note: "Local authority. Fourteen days. Needed before the first public performance.",
    },
    {
      id: "programme",
      name: "Send the programme to the printer",
      dept: "foh",
      owner: "Saffy Rowe",
      days: 1,
      wait: 10,
      depends: [],
      kind: "lead",
      external: true,
    },
    {
      id: "access",
      name: "Publish the access statement",
      dept: "foh",
      owner: "Saffy Rowe",
      days: 1,
      wait: 0,
      depends: [],
      kind: "work",
    },
    {
      id: "foyer",
      name: "Install the foyer",
      dept: "foh",
      owner: "Saffy Rowe",
      days: 1,
      wait: 0,
      depends: ["set-getout"],
      kind: "work",
    },
    {
      id: "foh-brief",
      name: "Brief the front-of-house staff",
      dept: "foh",
      owner: "Saffy Rowe",
      days: 1,
      wait: 0,
      depends: ["access"],
      kind: "work",
    },
    {
      id: "merch",
      name: "Order the merch print",
      dept: "foh",
      owner: "Saffy Rowe",
      days: 1,
      wait: 7,
      depends: [],
      kind: "lead",
      external: true,
    },
    {
      id: "house-ready",
      name: "House ready",
      dept: "foh",
      owner: "Saffy Rowe",
      days: 0,
      wait: 0,
      depends: ["foh-brief", "foyer", "access", "programme", "merch"],
      kind: "work",
    },
    {
      id: "press-seats",
      name: "Lock the press allocation",
      dept: "foh",
      owner: "Saffy Rowe",
      days: 1,
      wait: 0,
      depends: [],
      kind: "work",
    },
  ],
};

export const DEPT_LABEL: Record<import("./types").Dept, string> = {
  set: "Set",
  costume: "Costume",
  lx: "Lighting",
  sound: "Sound",
  props: "Props",
  cast: "Cast",
  foh: "Front of house",
};

export const DEPT_OWNER: Record<import("./types").Dept, string> = {
  set: "Jed",
  costume: "Anwen",
  lx: "Sol",
  sound: "Priya",
  props: "Kit",
  cast: "the company",
  foh: "Saffy",
};
