import { fact, none } from "./facts";
import type { Place } from "./types";

/**
 * Hand-written reaches. These are the records a person actually reads.
 * Every figure is modelled. Names are invented so a real weir is not
 * given a fictional death.
 */
export const WRITTEN: Place[] = [
  {
    slug: "hobbs-weir",
    name: "Hobb’s Weir",
    water: "river",
    waterName: "River Lynher",
    county: "Devon",
    nation: "England",
    sheet: "RCH 14 / 08",
    chainageKm: 11.4,
    summary:
      "A weir pool that looks still from the bank. The hydraulic holds a body under the sill and does not let go.",
    access: fact(
      "warden",
      "Left bank from the lane above Hobb’s Barton. A worn path to the apron. The right bank is private and fenced.",
      "2026-06-02",
    ),
    parking: fact(
      "warden",
      "Four cars on the verge by the cattle grid. No formal car park. Do not block the farm gate.",
      "2026-06-02",
    ),
    depth: fact(
      "warden",
      "Pool 2.5–4 m under the sill; shallow and rocky 30 m downstream.",
      "2025-08-19",
      "Sounded from the apron, not surveyed.",
    ),
    current: fact(
      "warden",
      "Recirculating hydraulic against the weir face in all seasons. The boil looks like slack water. It is not.",
      "2026-03-14",
    ),
    temperature: {
      spring: fact("sample", "9–11 °C", "2026-04-12", "Spot reading, mid-pool."),
      summer: fact("sample", "16–18 °C", "2025-08-19", "Spot reading, mid-pool."),
      autumn: fact("sample", "12–13 °C", "2025-10-08"),
      winter: fact("sample", "5–7 °C", "2026-01-22"),
    },
    quality: fact("sample", "sufficient", "2026-08-14"),
    qualityAfterRain:
      "Combined sewer overflow 400 m upstream at Hobb’s Barton. After 10 mm of rain the sample goes poor. Do not swim for 48 hours.",
    hazards: [
      {
        grade: "lethal",
        title: "Recirculating weir",
        body: "The pool below the sill holds a circulating current that has drowned people. From the bank it reads as a still, inviting basin. The hydraulic is there in August and in March. A person pulled under the sill cannot stand up and often cannot be reached from the apron.",
        seasonal:
          "August: the water looks benign and people jump. March: snowmelt, the same hydraulic, colder, stronger. Both kill.",
        afterRain: "Higher flow deepens the hold. After rain, stay out.",
      },
      {
        grade: "serious",
        title: "Cold shock in spring",
        body: "Even when the air is warm in April the water is still about 10 °C. A jump from the apron is a cold-shock risk before the weir is considered.",
      },
    ],
    legal: fact(
      "warden",
      "tolerated",
      "2024-07-01",
      "Not a designated bathing water. The landowner has not posted a prohibition. Access is along a public footpath to the bank.",
    ),
    childOk: false,
    mileOk: false,
    noCar: false,
    octoberOk: false,
    lengthM: fact("warden", 40, "2025-08-19", "Width of the pool only."),
    notes: [
      {
        by: "J.",
        date: "2025-08-12",
        text: "Went in from the left-hand rocks, not the apron. The boil under the weir pulled downstream then back. I was in for less than a minute and climbed out shaking. Do not jump from the sill.",
      },
    ],
  },
  {
    slug: "cinder-cut",
    name: "Cinder Cut",
    water: "river",
    waterName: "Old Fen Drain",
    county: "Norfolk",
    nation: "England",
    sheet: "RCH 03 / 21",
    chainageKm: 6.2,
    summary:
      "A straight cut through the fen. Almost nothing is recorded. A blank here is not a quiet reach.",
    access: none(),
    parking: none(),
    depth: none(),
    current: none(),
    temperature: {
      spring: none(),
      summer: none(),
      autumn: none(),
      winter: none(),
    },
    quality: none(),
    hazards: [
      {
        grade: "unknown",
        title: "This reach has not been assessed",
        body: "There is no warden record, no sounding, no current note, and no water-quality sample. Fen drains can be deep, steep-sided, and cold under a warm surface. Weirs and infalls are common and often unmarked. Do not read the emptiness of this page as an emptiness of hazard.",
      },
    ],
    legal: fact(
      "swimmer",
      "unclear",
      "2019-06-18",
      "The only mention of access is in the 2019 note. That is not a legal opinion.",
    ),
    childOk: null,
    mileOk: null,
    noCar: null,
    octoberOk: null,
    lengthM: none(),
    notes: [
      {
        by: "A. Pell",
        date: "2019-06-18",
        text: "Parked by the pumping station and walked the north bank. Got in where the reeds break, about ten minutes from the road. Brown water, couldn’t see my feet. Felt deep. No one else there. Nice evening.",
      },
    ],
  },
  {
    slug: "ladies-mile",
    name: "Ladies’ Mile",
    water: "lake",
    waterName: "Rigg Water",
    county: "Cumbria",
    nation: "England",
    sheet: "RCH 22 / 04",
    chainageKm: 1.8,
    summary:
      "A shelving shingle shore on the north side of Rigg Water. Sampled. Still a lake: cold below the first metre, and weather turns.",
    access: fact(
      "warden",
      "From the Rigg village bus stop, 12 minutes on the lakeshore path. Step-free to the shingle. No stile.",
      "2026-07-03",
    ),
    parking: fact(
      "warden",
      "Village hall car park, eight spaces, free. Overflow on the lane is not permitted on Sundays.",
      "2026-07-03",
    ),
    depth: fact(
      "sample",
      "Ankle to 1.2 m over the first 20 m; then a shelf to about 4 m.",
      "2026-06-11",
      "Waded and sounded. The shelf is abrupt.",
    ),
    current: fact(
      "warden",
      "None in ordinary weather. An easterly stacks a chop on this shore.",
      "2026-06-11",
    ),
    temperature: {
      spring: fact("sample", "8–10 °C", "2026-04-20"),
      summer: fact("sample", "16–18 °C", "2026-08-02"),
      autumn: fact("sample", "12–13 °C", "2025-10-14"),
      winter: fact("sample", "5–6 °C", "2026-01-09"),
    },
    quality: fact("sample", "excellent", "2026-08-02"),
    qualityAfterRain:
      "No overflow on this shore. After prolonged rain the inflows at the west end cloud the water; this mile usually stays clear a day longer.",
    hazards: [
      {
        grade: "caution",
        title: "Shelf and cold water",
        body: "The bottom drops from wading depth to about four metres in a few steps. Children who cannot swim must be kept inside the first twenty metres. The lake is cold below the surface even in August.",
        seasonal:
          "October readings are 12–13 °C. That is not a warm swim. Winter is a different activity.",
      },
    ],
    legal: fact(
      "sample",
      "designated",
      "2026-05-01",
      "Designated bathing water. Sampled through the modelled bathing season.",
    ),
    childOk: true,
    mileOk: true,
    noCar: true,
    octoberOk: false,
    lengthM: fact("warden", 1600, "2026-06-11", "Along the shore, in one’s depth for most of it if you stay inside the shelf."),
    notes: [
      {
        by: "M. Kane",
        date: "2026-08-02",
        text: "Swam with two children, seven and ten, inside the shelf. Water clear enough to see the drop. Bus from Penrith in the morning, back at four.",
      },
    ],
  },
  {
    slug: "rigg-strand",
    name: "Rigg Strand",
    water: "lake",
    waterName: "Rigg Water",
    county: "Cumbria",
    nation: "England",
    sheet: "RCH 22 / 05",
    chainageKm: 3.6,
    summary:
      "The long south shore. Two kilometres of open water if you want it, and a fetch when the wind is up.",
    access: fact(
      "warden",
      "Forestry track from Rigg South car park. Fifteen minutes. The last fifty metres are rooty.",
      "2026-07-03",
    ),
    parking: fact(
      "warden",
      "Rigg South, pay-and-display, forty spaces. Fills by ten on bank holidays.",
      "2026-07-03",
    ),
    depth: fact(
      "sample",
      "Deep quickly. 1.5 m at 8 m from shore; 12 m at 40 m.",
      "2025-09-01",
    ),
    current: fact(
      "warden",
      "No stream current. Wind-driven drift along the shore in a southerly.",
      "2026-07-03",
    ),
    temperature: {
      spring: fact("sample", "7–9 °C", "2026-04-20"),
      summer: fact("sample", "15–17 °C", "2026-08-02"),
      autumn: fact("sample", "11–12 °C", "2025-10-14"),
      winter: fact("sample", "5–6 °C", "2026-01-09"),
    },
    quality: fact("sample", "good", "2026-08-02"),
    hazards: [
      {
        grade: "caution",
        title: "Open water and fetch",
        body: "A mile here is a real mile, with no rest except the shore. In a south-westerly the chop builds. There is no patrol.",
        seasonal: "Autumn and spring: temperature is a hazard of its own.",
      },
    ],
    legal: fact("sample", "designated", "2026-05-01"),
    childOk: false,
    mileOk: true,
    noCar: false,
    octoberOk: false,
    lengthM: fact("warden", 2100, "2026-07-03", "South shore, buoy to the headland."),
    notes: [
      {
        by: "S. Rahman",
        date: "2026-07-19",
        text: "Did the two kilometres in a wet-suit in July. Sighted on the headland chimney. Boat traffic at weekends — keep a lane.",
      },
    ],
  },
  {
    slug: "st-agnes-lido",
    name: "St Agnes Lido",
    water: "lido",
    waterName: "St Agnes Lido",
    county: "Cornwall",
    nation: "England",
    sheet: "RCH 31 / 02",
    chainageKm: 0,
    summary:
      "A municipal salt-water lido on the branch line. Heated into October. The one reach in this county you can reach without a car and still know the temperature.",
    access: fact(
      "warden",
      "From St Agnes station, 6 minutes downhill. Step-free via the service road. Gates 07:00–19:00 in season.",
      "2026-08-01",
    ),
    parking: fact(
      "warden",
      "None reserved for the lido. The station has a dozen spaces. Most people come by train.",
      "2026-08-01",
    ),
    depth: fact(
      "sample",
      "0.9 m in the shallow bay; 1.8 m in the main tank.",
      "2026-05-12",
      "Painted on the walls. Confirmed.",
    ),
    current: fact("warden", "None. Enclosed tank.", "2026-05-12"),
    temperature: {
      spring: fact("sample", "16 °C heated", "2026-04-15"),
      summer: fact("sample", "19 °C heated", "2026-08-10"),
      autumn: fact("sample", "16 °C heated, to the last Sunday in October", "2025-10-26"),
      winter: fact("warden", "Closed", "2026-01-01"),
    },
    quality: fact("sample", "excellent", "2026-08-10"),
    hazards: [
      {
        grade: "caution",
        title: "Ordinary pool hazards",
        body: "A lido, not a wild swim: slip on wet stone, depth change at the rope, no lifeguard after 17:00 on weekdays. The sea is the other side of the wall and is a different entry entirely.",
      },
    ],
    legal: fact("sample", "designated", "2026-05-01"),
    childOk: true,
    mileOk: false,
    noCar: true,
    octoberOk: true,
    lengthM: fact("sample", 50, "2026-05-12"),
    notes: [
      {
        by: "Priya N.",
        date: "2025-10-18",
        text: "Last warm swim of the year. Train from Truro, towel in a backpack. The heating was on. The sea next door was not tempting.",
      },
    ],
  },
  {
    slug: "greta-outfall",
    name: "Greta Outfall",
    water: "river",
    waterName: "River Greta",
    county: "County Durham",
    nation: "England",
    sheet: "RCH 09 / 16",
    chainageKm: 18.7,
    summary:
      "A popular bend below the town. Sampled as poor after rain because of the storm overflow at the outfall itself.",
    access: fact(
      "warden",
      "Town path from Greta Bridge, 8 minutes. Steps down, no handrail on the last flight.",
      "2026-07-21",
    ),
    parking: fact(
      "warden",
      "Bridge Street long-stay. Or the train: Greta Halt is 11 minutes on foot.",
      "2026-07-21",
    ),
    depth: fact("warden", "1–1.8 m in the bend; deeper under the far alder.", "2025-07-02"),
    current: fact(
      "warden",
      "Moderate in summer. After rain the bend becomes a single tongue and the eddy on the inside bank is unreliable.",
      "2026-03-02",
    ),
    temperature: {
      spring: fact("sample", "8–10 °C", "2026-04-03"),
      summer: fact("sample", "15–17 °C", "2026-07-21"),
      autumn: fact("sample", "11 °C", "2025-10-02"),
      winter: none(),
    },
    quality: fact("sample", "poor", "2026-08-20"),
    qualityAfterRain:
      "The named overflow discharges at this bend. A sample taken 6 hours after 15 mm of rain was poor. The sign on the path is often turned to face the hedge. Treat any rain in the last day as a reason to stay out.",
    hazards: [
      {
        grade: "serious",
        title: "Storm overflow at the swim",
        body: "This is not a distant upstream risk. The outfall pipe is the left-bank concrete the path uses as a landmark. After rain the water is sewage-contaminated. People still swim here because it is close to town.",
        afterRain: "Stay out for at least 48 hours after significant rain. If the pipe is running, stay out regardless of the forecast.",
      },
      {
        grade: "caution",
        title: "Steps and current",
        body: "The last flight of steps is wet and has no rail. In spate the landing is underwater.",
      },
    ],
    legal: fact("warden", "tolerated", "2025-06-01"),
    childOk: false,
    mileOk: false,
    noCar: true,
    octoberOk: false,
    lengthM: fact("warden", 80, "2025-07-02"),
    notes: [
      {
        by: "Tom H.",
        date: "2024-09-03",
        text: "Swam the day after a dry week. Fine. Came back in October after rain because I was lazy about checking. The water smelled. That is on me.",
      },
    ],
  },
  {
    slug: "blackrock-steps",
    name: "Blackrock Steps",
    water: "coast",
    waterName: "Irish Sea",
    county: "Pembrokeshire",
    nation: "Wales",
    sheet: "RCH 40 / 11",
    chainageKm: 0,
    summary:
      "A cut stair in the cliff to a dark slot. Rip along the north wall on the ebb. Not a beginner’s sea.",
    access: fact(
      "warden",
      "Coast path from Blackrock farm, 20 minutes. The steps are cut stone, 68 of them, slick with weed at the bottom.",
      "2026-05-28",
    ),
    parking: fact("warden", "Farm field, honesty box, twelve cars. Gate locked at dusk.", "2026-05-28"),
    depth: fact(
      "warden",
      "Entry is into 2–3 m at mid tide. At low water the slot is a gully of rocks.",
      "2025-08-30",
    ),
    current: fact(
      "warden",
      "Rip along the north wall on the ebb, running west. Slack is short, about 40 minutes after high water on a neap.",
      "2026-05-28",
    ),
    temperature: {
      spring: fact("sample", "9–10 °C", "2026-04-18"),
      summer: fact("sample", "14–16 °C", "2025-08-30"),
      autumn: fact("sample", "13–14 °C", "2025-10-11"),
      winter: fact("sample", "8 °C", "2026-01-15"),
    },
    quality: fact("sample", "good", "2026-06-02"),
    hazards: [
      {
        grade: "serious",
        title: "Rip on the ebb",
        body: "The slot looks sheltered. On the ebb a rip runs out along the north wall. Several swimmers have been taken beyond the point and had to be collected by boat. If you cannot read a tide table, this is not your entry.",
        seasonal: "Autumn swell makes the steps themselves the hazard. Winter is not a swimming entry.",
      },
    ],
    legal: fact("warden", "legal", "2025-01-01", "Foreshore access. Not designated."),
    childOk: false,
    mileOk: false,
    noCar: false,
    octoberOk: false,
    lengthM: fact("warden", 300, "2025-08-30", "Along the wall to the point, in settled weather only."),
    notes: [
      {
        by: "Catriona",
        date: "2025-08-30",
        text: "Neap, an hour after high. Clear and cold. Did not stay for the ebb. The steps were already greasy.",
      },
    ],
  },
  {
    slug: "polkerris-basin",
    name: "Polkerris Basin",
    water: "tidal-pool",
    waterName: "Polkerris Basin",
    county: "Cornwall",
    nation: "England",
    sheet: "RCH 31 / 09",
    chainageKm: 0,
    summary:
      "A walled basin that fills on the flood. Empty of water — and of meaning as a swim — on a spring low.",
    access: fact(
      "warden",
      "Village street to the harbour wall, 4 minutes from the bus. Cobbled, uneven, no step-free route into the basin.",
      "2026-06-20",
    ),
    parking: fact(
      "warden",
      "Village car park, expensive in summer, a mile’s walk if full. Bus from St Austell in season.",
      "2026-06-20",
    ),
    depth: fact(
      "warden",
      "1.4 m at the ladder on an ordinary high water. A few centimetres at spring low. Do not guess; read the tide.",
      "2026-06-20",
    ),
    current: fact(
      "warden",
      "Fills and empties through the sluice in the east wall. Do not sit in the sluice on a falling tide.",
      "2026-06-20",
    ),
    temperature: {
      spring: fact("sample", "11 °C", "2026-04-22"),
      summer: fact("sample", "16–17 °C", "2026-08-08"),
      autumn: fact("sample", "14 °C", "2025-10-09"),
      winter: fact("sample", "9 °C", "2026-01-11"),
    },
    quality: fact("sample", "good", "2026-08-08"),
    qualityAfterRain:
      "A small stream enters at the west corner. After heavy rain the basin clouds; it is not on a sewer overflow.",
    hazards: [
      {
        grade: "caution",
        title: "Tide and sluice",
        body: "The basin is a swim only in the upper half of the tide. The sluice is a trap on the ebb. Weed on the ladder.",
      },
    ],
    legal: fact("sample", "designated", "2026-05-01"),
    childOk: true,
    mileOk: false,
    noCar: true,
    octoberOk: true,
    lengthM: fact("warden", 60, "2026-06-20"),
    notes: [
      {
        by: "Ellis",
        date: "2026-08-08",
        text: "High water at noon, children in the basin, adults looking at the sea. The ladder needs a scrape.",
      },
    ],
  },
  {
    slug: "easter-lough",
    name: "Easter Lough",
    water: "lake",
    waterName: "Easter Lough",
    county: "Donegal",
    nation: "Ireland",
    sheet: "RCH 51 / 03",
    chainageKm: 0,
    summary:
      "A small lough at the end of a bog road. One note, no sample, no sounding. The silence on this page is the point.",
    access: fact(
      "swimmer",
      "Bog road from the R-road, then a sheep track. The 2021 note does not say how long.",
      "2021-07-09",
    ),
    parking: none(),
    depth: none(),
    current: none(),
    temperature: {
      spring: none(),
      summer: none(),
      autumn: none(),
      winter: none(),
    },
    quality: none(),
    hazards: [
      {
        grade: "unknown",
        title: "Unsounded peat lake",
        body: "Peat loughs are often suddenly deep, with soft bottoms and water too dark to see a submerged fence or a shelf. Nothing here has been measured. The single note is five years old and describes a mood, not a depth.",
      },
    ],
    legal: fact("swimmer", "unclear", "2021-07-09"),
    childOk: null,
    mileOk: null,
    noCar: null,
    octoberOk: null,
    lengthM: none(),
    notes: [
      {
        by: "Niamh",
        date: "2021-07-09",
        text: "Came over the hill in the evening. Brown water, warm on top. Floated. Midges. Would go back.",
      },
    ],
  },
  {
    slug: "holme-mill-pool",
    name: "Holme Mill Pool",
    water: "river",
    waterName: "River Dove",
    county: "Derbyshire",
    nation: "England",
    sheet: "RCH 18 / 07",
    chainageKm: 22.1,
    summary:
      "The mill is gone. The weir is not. A pretty pool under trees, and a known drowning site.",
    access: fact(
      "warden",
      "Footpath from Holme village green, 7 minutes. The last descent is a mud slide after rain.",
      "2026-06-14",
    ),
    parking: fact("warden", "Village only. No riverside parking. Two buses a day from Buxton.", "2026-06-14"),
    depth: fact("warden", "Pool to 3 m. The weir face is undercut.", "2024-09-12"),
    current: fact(
      "warden",
      "Recirculating hold at the weir in medium and high water. In drought the hold weakens but the undercut remains.",
      "2026-02-18",
    ),
    temperature: {
      spring: fact("sample", "8 °C", "2026-04-09"),
      summer: fact("sample", "15 °C", "2025-08-16"),
      autumn: none(),
      winter: none(),
    },
    quality: fact("sample", "good", "2025-08-16"),
    hazards: [
      {
        grade: "lethal",
        title: "Mill weir, undercut",
        body: "People have drowned here. The hold is less famous than some, which makes it worse: visitors treat it as a swimming hole because of the trees and the stone. The weir is still a weir.",
        seasonal:
          "Summer drought: the pool looks like a pond. The undercut is still there. Winter and spring: stay away.",
      },
    ],
    legal: fact("warden", "tolerated", "2023-01-01"),
    childOk: false,
    mileOk: false,
    noCar: false,
    octoberOk: null,
    lengthM: fact("warden", 25, "2024-09-12"),
    notes: [],
  },
  {
    slug: "the-long-cut",
    name: "The Long Cut",
    water: "river",
    waterName: "Kepp Canal",
    county: "Oxfordshire",
    nation: "England",
    sheet: "RCH 12 / 02",
    chainageKm: 4.0,
    summary:
      "A dead-straight navigation cut. A mile is a mile here, with almost no current, and a towpath the whole way.",
    access: fact(
      "warden",
      "Towpath from Kepp Halt (train). Step-free. Get in at the old winding hole, marked by a rusted ladder.",
      "2026-07-11",
    ),
    parking: fact("warden", "Halt car park, 20 spaces. Or the train.", "2026-07-11"),
    depth: fact("sample", "1.4–1.8 m, uniform. Silt on the bed.", "2026-06-01"),
    current: fact("warden", "Slack. A lock filling a mile up can put a brief draw on the cut.", "2026-07-11"),
    temperature: {
      spring: fact("sample", "11 °C", "2026-04-28"),
      summer: fact("sample", "18–20 °C", "2026-08-05"),
      autumn: fact("sample", "14 °C", "2025-10-12"),
      winter: fact("sample", "6 °C", "2026-01-20"),
    },
    quality: fact("sample", "sufficient", "2026-08-05"),
    qualityAfterRain:
      "Boats and a small works outfall. After rain the cut is murky rather than sewage-led, but do not swallow it.",
    hazards: [
      {
        grade: "caution",
        title: "Boats, silt, leptospirosis",
        body: "Narrowboats have right of way and limited sight-lines. The silt is deep enough to lose a shoe. This is canal water: cover cuts, and do not treat ‘sufficient’ as drinking water.",
      },
    ],
    legal: fact("warden", "legal", "2025-01-01", "Navigation. Swimming is not forbidden on this pound."),
    childOk: false,
    mileOk: true,
    noCar: true,
    octoberOk: true,
    lengthM: fact("warden", 1700, "2026-07-11", "Winding hole to the next bridge."),
    notes: [
      {
        by: "R. Okoye",
        date: "2026-08-05",
        text: "Early, before the boats. One mile out and back in a skin-suit. The ladder is the only civilised exit.",
      },
    ],
  },
  {
    slug: "toilers-ford",
    name: "Toiler’s Ford",
    water: "river",
    waterName: "River Usk",
    county: "Powys",
    nation: "Wales",
    sheet: "RCH 27 / 14",
    chainageKm: 31.0,
    summary:
      "A named ford on the map, and almost nothing else. The 2018 note is not a depth.",
    access: fact(
      "swimmer",
      "Lane to the old ford. The note says ‘obvious’. That was eight years ago.",
      "2018-09-02",
    ),
    parking: none(),
    depth: none(),
    current: fact(
      "swimmer",
      "‘Knee deep and pushy after rain’ — one sentence, 2018. Not a measurement.",
      "2018-09-02",
    ),
    temperature: {
      spring: none(),
      summer: none(),
      autumn: none(),
      winter: none(),
    },
    quality: none(),
    hazards: [
      {
        grade: "unknown",
        title: "A ford is not a swim",
        body: "Fords exist because the river is shallow enough for a cart on a good day. That tells you nothing about the hole on the downstream side, or the current after rain. There is no recent record.",
      },
    ],
    legal: fact("swimmer", "unclear", "2018-09-02"),
    childOk: null,
    mileOk: null,
    noCar: null,
    octoberOk: null,
    lengthM: none(),
    notes: [
      {
        by: "Anon",
        date: "2018-09-02",
        text: "Crossed after a dry August. Knee deep and pushy after rain, someone in the pub said. I was there on a dry day. Pretty.",
      },
    ],
  },
  {
    slug: "pentreath-lido",
    name: "Pentreath Lido",
    water: "lido",
    waterName: "Pentreath Lido",
    county: "Cornwall",
    nation: "England",
    sheet: "RCH 31 / 14",
    chainageKm: 0,
    summary:
      "Heated municipal tank on the cliff road. Open into October. You need a car or a determined bus.",
    access: fact("warden", "Cliff road entrance. Stairs to the tank. No lift.", "2026-07-01"),
    parking: fact("warden", "Shared with the hotel, thirty spaces, charged.", "2026-07-01"),
    depth: fact("sample", "1.0 m / 1.8 m, marked.", "2026-05-01"),
    current: fact("warden", "None.", "2026-05-01"),
    temperature: {
      spring: fact("sample", "17 °C heated", "2026-04-10"),
      summer: fact("sample", "20 °C heated", "2026-08-01"),
      autumn: fact("sample", "17 °C heated, closes 31 October", "2025-10-31"),
      winter: fact("warden", "Closed", "2026-01-01"),
    },
    quality: fact("sample", "excellent", "2026-08-01"),
    hazards: [
      {
        grade: "caution",
        title: "Stairs and cliff edge",
        body: "The tank is safe in the ordinary way. The walk from the car park passes an unfenced drop. After 18:00 there is no attendant.",
      },
    ],
    legal: fact("sample", "designated", "2026-05-01"),
    childOk: true,
    mileOk: false,
    noCar: false,
    octoberOk: true,
    lengthM: fact("sample", 33, "2026-05-01"),
    notes: [],
  },
  {
    slug: "newlyn-steps",
    name: "Newlyn Steps",
    water: "coast",
    waterName: "Mount’s Bay",
    county: "Cornwall",
    nation: "England",
    sheet: "RCH 31 / 18",
    chainageKm: 0,
    summary:
      "Harbour steps used by swimmers who get off the train. A working harbour, not a beach.",
    access: fact(
      "warden",
      "From Newlyn Bridge stop or Penzance station (25 minutes on foot). The steps are the third set past the fish market.",
      "2026-06-08",
    ),
    parking: fact("warden", "Do not park at the market. Use the town car parks and walk.", "2026-06-08"),
    depth: fact("warden", "Steps enter into about 1.5 m at half tide. Prop-wash when boats move.", "2026-06-08"),
    current: fact(
      "warden",
      "Harbour water is mostly slack. Outside the wall, a longshore drift to the east on the flood.",
      "2026-06-08",
    ),
    temperature: {
      spring: fact("sample", "10 °C", "2026-04-16"),
      summer: fact("sample", "15–16 °C", "2026-08-11"),
      autumn: fact("sample", "14 °C", "2025-10-07"),
      winter: fact("sample", "9 °C", "2026-01-18"),
    },
    quality: fact("sample", "sufficient", "2026-08-11"),
    qualityAfterRain:
      "Harbour and town drains. After rain the corner by the market is the worst of it. Swim off the outer steps or not at all.",
    hazards: [
      {
        grade: "serious",
        title: "Working harbour",
        body: "Boats, ropes, fuel, and men who are not looking for swimmers. Stay inside the agreed corner. Do not cross the harbour mouth.",
      },
      {
        grade: "caution",
        title: "Steps and weed",
        body: "The lower treads disappear under slime. Exit is harder than entry.",
      },
    ],
    legal: fact("warden", "tolerated", "2025-03-01", "The harbour master knows. Stay where you are expected."),
    childOk: false,
    mileOk: false,
    noCar: true,
    octoberOk: true,
    lengthM: fact("warden", 120, "2026-06-08"),
    notes: [
      {
        by: "Jen",
        date: "2026-08-11",
        text: "Train to Penzance, walked. In and out before the boats moved. The water was clearer than I expected for a harbour.",
      },
    ],
  },
  {
    slug: "the-baths",
    name: "The Baths",
    water: "lake",
    waterName: "Nant-y-Bai spring",
    county: "Powys",
    nation: "Wales",
    sheet: "RCH 27 / 22",
    chainageKm: 0.4,
    summary:
      "A modelled warm spring feeding a stone tank in the trees. The warmth is the reason people come in October. It is still a rural tank, not a spa.",
    access: fact(
      "warden",
      "Marked path from the chapel car park, 10 minutes. The last stile is high.",
      "2026-05-19",
    ),
    parking: fact("warden", "Chapel, eight cars. Do not use the farmyard.", "2026-05-19"),
    depth: fact("sample", "1.1 m, even.", "2026-05-19"),
    current: fact("warden", "A trickle through. Not a current that moves a body.", "2026-05-19"),
    temperature: {
      spring: fact("sample", "16 °C", "2026-04-11", "Spring-fed. Air temperature does little."),
      summer: fact("sample", "17 °C", "2026-07-22"),
      autumn: fact("sample", "16 °C", "2025-10-19"),
      winter: fact("sample", "14 °C", "2026-01-08"),
    },
    quality: fact("sample", "good", "2026-07-22"),
    hazards: [
      {
        grade: "caution",
        title: "Algae and isolation",
        body: "In a hot summer the tank greens. There is no phone signal in the hollow. You are a mile from the road if something goes wrong.",
      },
    ],
    legal: fact("warden", "tolerated", "2024-01-01"),
    childOk: true,
    mileOk: false,
    noCar: false,
    octoberOk: true,
    lengthM: fact("sample", 18, "2026-05-19"),
    notes: [
      {
        by: "Owen",
        date: "2025-10-19",
        text: "Sixteen degrees in October felt like a gift. The walk back in wet clothes did not.",
      },
    ],
  },
  {
    slug: "quarry-at-mortham",
    name: "Quarry at Mortham",
    water: "lake",
    waterName: "Mortham Quarry",
    county: "North Yorkshire",
    nation: "England",
    sheet: "RCH 08 / 19",
    chainageKm: 0,
    summary:
      "A flooded limestone quarry. Turquoise in photographs. A shelf, then a hole, and water that stays cold.",
    access: fact(
      "warden",
      "From Mortham village, the old works road. A gap in the fence that everyone uses. This is not an invitation.",
      "2026-06-30",
    ),
    parking: fact("warden", "Village street only. Vans have been ticketed.", "2026-06-30"),
    depth: fact(
      "sample",
      "Shelf at 1.5 m for about 8 m, then a drop to 18 m. The drop is not marked.",
      "2024-08-03",
      "Dive-club sounding, two years old.",
    ),
    current: fact("warden", "None.", "2026-06-30"),
    temperature: {
      spring: fact("sample", "7 °C at 2 m", "2026-04-25"),
      summer: fact("sample", "14 °C at the surface; 8 °C at 4 m", "2025-08-14"),
      autumn: fact("sample", "11 °C surface", "2025-10-03"),
      winter: none(),
    },
    quality: fact("sample", "excellent", "2025-08-14"),
    hazards: [
      {
        grade: "serious",
        title: "Unmarked deep water",
        body: "The colour makes people jump. The shelf is short. Cold at depth in August is a cramp risk. There are submerged blocks on the west side.",
        seasonal: "Spring surface temperatures are winter temperatures. Do not jump.",
      },
    ],
    legal: fact(
      "warden",
      "forbidden",
      "2025-04-01",
      "The owner has posted the quarry. The gap in the fence is not permission. Listed here so the prohibition is as findable as the photographs.",
    ),
    childOk: false,
    mileOk: false,
    noCar: false,
    octoberOk: false,
    lengthM: fact("sample", 90, "2024-08-03"),
    notes: [
      {
        by: "Dive club (file note)",
        date: "2024-08-03",
        text: "Sounded the east shelf. Please stop describing this as a swimming lake. It is a hole full of water.",
      },
    ],
  },
  {
    slug: "winterbourne-weir",
    name: "Winterbourne Weir",
    water: "river",
    waterName: "River Frome",
    county: "Dorset",
    nation: "England",
    sheet: "RCH 16 / 05",
    chainageKm: 8.3,
    summary:
      "A low weir in a pretty village. Low weirs kill more people than high ones, because they look like nothing.",
    access: fact("warden", "Church lane to the bridge, then the left-bank meadow. Public footpath.", "2026-05-04"),
    parking: fact("warden", "Church, Sunday excepted. The pub will tow.", "2026-05-04"),
    depth: fact("warden", "0.8 m above; 1.6 m in the pool. The sill is 400 mm.", "2025-07-18"),
    current: fact(
      "warden",
      "A keepers’ weir: the hold is shallow and surprisingly strong. Dogs have died here. So have people.",
      "2026-01-30",
    ),
    temperature: {
      spring: fact("sample", "10 °C", "2026-04-07"),
      summer: fact("sample", "17 °C", "2025-07-18"),
      autumn: fact("sample", "13 °C", "2025-10-06"),
      winter: fact("sample", "6 °C", "2026-01-30"),
    },
    quality: fact("sample", "good", "2025-07-18"),
    hazards: [
      {
        grade: "lethal",
        title: "Low weir, strong hold",
        body: "The sill is barely knee-high. The circulating current on the downstream face has held adults and dogs against the stone. Village photographs make it look like a paddling place. It is not.",
        seasonal: "Any season with water over the sill. In a dry July the hold can still be enough.",
      },
    ],
    legal: fact("warden", "tolerated", "2024-01-01"),
    childOk: false,
    mileOk: false,
    noCar: false,
    octoberOk: false,
    lengthM: fact("warden", 15, "2025-07-18"),
    notes: [],
  },
  {
    slug: "borth-haven",
    name: "Borth Haven",
    water: "tidal-pool",
    waterName: "Borth Haven",
    county: "Ceredigion",
    nation: "Wales",
    sheet: "RCH 28 / 06",
    chainageKm: 0,
    summary:
      "A natural trough in the reef, improved with a little concrete. Quality collapses after rain because of the stream that feeds the village.",
    access: fact("warden", "Promenade, then the reef path. Possible with a buggy to the wall, not to the water.", "2026-07-08"),
    parking: fact("warden", "Promenade pay-and-display. Train to Borth, 8 minutes on foot.", "2026-07-08"),
    depth: fact("warden", "1.2 m at high water in the trough. Rocks at low water.", "2026-07-08"),
    current: fact("warden", "A wash through on the ebb. Not a rip, but enough to move a child toward the open side.", "2026-07-08"),
    temperature: {
      spring: fact("sample", "10 °C", "2026-04-14"),
      summer: fact("sample", "16 °C", "2026-08-04"),
      autumn: fact("sample", "14 °C", "2025-10-10"),
      winter: none(),
    },
    quality: fact("sample", "poor", "2026-08-18"),
    qualityAfterRain:
      "Village stream and a known overflow after 12 mm. The bathing-water sign on the promenade is for the beach, not this trough, and is often the opposite colour.",
    hazards: [
      {
        grade: "serious",
        title: "Water quality after rain",
        body: "Families treat this as a paddling pool. After rain it is not. The last two poor samples followed wet weekends in the school holidays.",
        afterRain: "If the stream at the slip is brown or smelling, the trough is the same water.",
      },
      {
        grade: "caution",
        title: "Reef and ebb",
        body: "Rock ledges, urchins, and a pull toward the open side as the tide leaves.",
      },
    ],
    legal: fact("sample", "designated", "2026-05-01", "The designation is the beach. The trough is used as if it were included."),
    childOk: false,
    mileOk: false,
    noCar: true,
    octoberOk: true,
    lengthM: fact("warden", 40, "2026-07-08"),
    notes: [
      {
        by: "Sian",
        date: "2025-08-22",
        text: "We paddled after a Friday storm because the beach flag was green. Two children were ill that night. I am writing this so the next person does not do the same.",
      },
    ],
  },
  {
    slug: "kelvingrove-steps",
    name: "Kelvingrove Steps",
    water: "river",
    waterName: "River Kelvin",
    county: "Glasgow",
    nation: "Scotland",
    sheet: "RCH 02 / 01",
    chainageKm: 5.5,
    summary:
      "City steps to a river that is not a lido. No car needed. A current, a wall, and water quality that follows the city’s rain.",
    access: fact(
      "warden",
      "From Kelvinbridge subway, 4 minutes. The steps are public. Exit is the same steps; there is no shallow beach.",
      "2026-07-15",
    ),
    parking: fact("warden", "None that you want. Come by subway.", "2026-07-15"),
    depth: fact("warden", "Wall is vertical into about 2 m. No wading entry.", "2026-07-15"),
    current: fact(
      "warden",
      "Always some. After rain, enough to take a weak swimmer under the bridge.",
      "2026-07-15",
    ),
    temperature: {
      spring: fact("sample", "8 °C", "2026-04-05"),
      summer: fact("sample", "16 °C", "2026-08-09"),
      autumn: fact("sample", "12 °C", "2025-10-04"),
      winter: fact("sample", "5 °C", "2026-01-12"),
    },
    quality: fact("sample", "sufficient", "2026-08-09"),
    qualityAfterRain:
      "Urban river. After rain assume poor, whether or not a sample has caught up.",
    hazards: [
      {
        grade: "serious",
        title: "Vertical wall, city current",
        body: "You get in by dropping from the steps. You get out the same way, with cold hands. After rain the current sets toward the bridge piers.",
        afterRain: "Do not swim. The Kelvin rises quickly.",
      },
    ],
    legal: fact("warden", "tolerated", "2025-01-01"),
    childOk: false,
    mileOk: false,
    noCar: true,
    octoberOk: false,
    lengthM: fact("warden", 200, "2026-07-15", "Steps to the next bridge, in settled low water only."),
    notes: [
      {
        by: "A. Mac",
        date: "2026-08-09",
        text: "Early Tuesday. Two others. We stay between the steps and the first buoy. This is not a place to show anyone.",
      },
    ],
  },
  {
    slug: "the-cob-pool",
    name: "The Cob Pool",
    water: "tidal-pool",
    waterName: "The Cob",
    county: "Gwynedd",
    nation: "Wales",
    sheet: "RCH 26 / 08",
    chainageKm: 0,
    summary:
      "A pool against the cob wall that only exists for a few hours. People write about it as if it were permanent.",
    access: fact("warden", "From the station, along the cob, 9 minutes. Exposed in a westerly.", "2026-06-17"),
    parking: fact("warden", "Station yard. Trains are the point.", "2026-06-17"),
    depth: fact("warden", "About 1.3 m at a good high water. Absent at low water.", "2026-06-17"),
    current: fact("warden", "Fills from the estuary. On the ebb the pool drains through a gap at the north end — sit there and you go with it.", "2026-06-17"),
    temperature: {
      spring: none(),
      summer: fact("sample", "16 °C", "2025-08-21"),
      autumn: none(),
      winter: none(),
    },
    quality: fact("sample", "good", "2025-08-21"),
    hazards: [
      {
        grade: "caution",
        title: "A pool that disappears",
        body: "If you do not know the tide you will arrive to mud. The drain gap is the hazard when the water is in.",
      },
    ],
    legal: fact("warden", "legal", "2025-01-01"),
    childOk: true,
    mileOk: false,
    noCar: true,
    octoberOk: null,
    lengthM: fact("warden", 35, "2026-06-17"),
    notes: [
      {
        by: "Bethan",
        date: "2025-08-21",
        text: "High water at 11. Children happy. Two hours later we were walking on sand that had been the swim.",
      },
    ],
  },
  {
    slug: "whiteadder-haugh",
    name: "Whiteadder Haugh",
    water: "river",
    waterName: "Whiteadder Water",
    county: "Scottish Borders",
    nation: "Scotland",
    sheet: "RCH 06 / 12",
    chainageKm: 14.2,
    summary:
      "A loop of river around a haugh. Room to swim a mile if the water is low enough to be kind, which it often is not.",
    access: fact("warden", "Farm track from the kirk, then the haugh gate. The farmer has asked that the gate be shut.", "2026-06-25"),
    parking: fact("warden", "Kirk, six cars. Sundays are impossible.", "2026-06-25"),
    depth: fact("warden", "0.8–1.6 m in summer low. Holes on the outside of the bend to about 2.5 m.", "2025-07-29"),
    current: fact("warden", "Gentle in a dry July. A different river after rain in the Lammermuirs.", "2026-06-25"),
    temperature: {
      spring: fact("sample", "8 °C", "2026-04-17"),
      summer: fact("sample", "15–16 °C", "2025-07-29"),
      autumn: fact("sample", "11 °C", "2025-10-01"),
      winter: none(),
    },
    quality: fact("sample", "good", "2025-07-29"),
    hazards: [
      {
        grade: "caution",
        title: "Rain in the hills",
        body: "The forecast in the valley can be wrong. If the water is the colour of tea with milk, do not start a mile.",
      },
    ],
    legal: fact("warden", "legal", "2025-01-01", "Access rights. Shut the gate."),
    childOk: false,
    mileOk: true,
    noCar: false,
    octoberOk: false,
    lengthM: fact("warden", 1800, "2025-07-29", "Around the haugh and back, in summer low only."),
    notes: [
      {
        by: "Fiona",
        date: "2025-07-29",
        text: "A true mile in July. Saw a heron and a tractor. The exit at the gate is the only one that is not nettles.",
      },
    ],
  },
  {
    slug: "fowey-saltings",
    name: "Fowey Saltings",
    water: "coast",
    waterName: "Fowey estuary",
    county: "Cornwall",
    nation: "England",
    sheet: "RCH 31 / 21",
    chainageKm: 2.1,
    summary:
      "A muddy estuary swim at high water. At any other tide it is a walk in sinking mud.",
    access: fact("warden", "Creekside path from the ferry. Boots, not sandals, until you swim.", "2026-07-02"),
    parking: fact("warden", "Town, then the ferry. Do not drive the creek lane.", "2026-07-02"),
    depth: fact("warden", "1–2 m over the channel at high water. Mud to the knee at half tide.", "2026-07-02"),
    current: fact("warden", "Estuary flood and ebb. Slack is brief. The channel is used by boats.", "2026-07-02"),
    temperature: {
      spring: none(),
      summer: fact("sample", "17 °C", "2025-08-19"),
      autumn: fact("sample", "15 °C", "2025-10-08"),
      winter: none(),
    },
    quality: fact("sample", "sufficient", "2025-08-19"),
    hazards: [
      {
        grade: "serious",
        title: "Mud and boats",
        body: "The mud can hold a person. The channel is a navigation. This is a high-water-only swim, and even then you are a head in a fairway.",
      },
    ],
    legal: fact("warden", "tolerated", "2024-01-01"),
    childOk: false,
    mileOk: false,
    noCar: true,
    octoberOk: true,
    lengthM: fact("warden", 400, "2026-07-02"),
    notes: [],
  },
  {
    slug: "dove-dale-pool",
    name: "Dove Dale Pool",
    water: "river",
    waterName: "River Dove",
    county: "Staffordshire",
    nation: "England",
    sheet: "RCH 18 / 11",
    chainageKm: 16.4,
    summary:
      "A famous-looking pool in a gorge. The current on the far side is the reason it is not a children’s place.",
    access: fact("warden", "National path, 25 minutes from the dale car park. Crowded on summer Sundays.", "2026-06-19"),
    parking: fact("warden", "Dale car park, often full by 09:30. No other legal parking.", "2026-06-19"),
    depth: fact("warden", "1.2 m this side; 2.5 m and a seam of current under the far limestone.", "2025-08-01"),
    current: fact(
      "warden",
      "The far-side seam will move a competent swimmer downstream. The near side is deceptively calm.",
      "2025-08-01",
    ),
    temperature: {
      spring: fact("sample", "8 °C", "2026-04-08"),
      summer: fact("sample", "14 °C", "2025-08-01"),
      autumn: none(),
      winter: none(),
    },
    quality: fact("sample", "excellent", "2025-08-01"),
    hazards: [
      {
        grade: "serious",
        title: "Two rivers in one pool",
        body: "The photograph is of the near side. The far side is a different problem. People cross for the photo and discover the seam halfway.",
      },
    ],
    legal: fact("warden", "legal", "2025-01-01"),
    childOk: false,
    mileOk: false,
    noCar: false,
    octoberOk: null,
    lengthM: fact("warden", 50, "2025-08-01"),
    notes: [
      {
        by: "Mark T.",
        date: "2025-08-01",
        text: "I am a strong swimmer and I still felt the far side as a surprise. Stay this side or do not go in.",
      },
    ],
  },
  {
    slug: "llyn-cerrig",
    name: "Llyn Cerrig",
    water: "lake",
    waterName: "Llyn Cerrig",
    county: "Gwynedd",
    nation: "Wales",
    sheet: "RCH 26 / 15",
    chainageKm: 0,
    summary:
      "An upland lake, reached on foot. A mile is available. The temperature in October is not a swimming temperature for most people, and it has been measured.",
    access: fact("warden", "Mountain path from the road-end, 40 minutes. Not a family stroll.", "2026-06-03"),
    parking: fact("warden", "Road-end lay-by, five cars. Full means you walk further; do not verge-park on the pass.", "2026-06-03"),
    depth: fact("sample", "Deep. 2 m within a few strokes of the east shore.", "2024-09-20"),
    current: fact("warden", "None, except wind.", "2026-06-03"),
    temperature: {
      spring: fact("sample", "6 °C", "2026-05-02"),
      summer: fact("sample", "13–14 °C", "2025-08-12"),
      autumn: fact("sample", "9 °C", "2025-10-15"),
      winter: fact("sample", "4 °C", "2026-01-05"),
    },
    quality: fact("sample", "excellent", "2025-08-12"),
    hazards: [
      {
        grade: "caution",
        title: "Cold, remote, weather",
        body: "A mile in 13 °C with a walk-out in wet clothes is an expedition. Cloud comes down on this lake without much warning. October at 9 °C is for people who already know they swim in 9 °C.",
        seasonal: "We will not list this as warm enough in October. The number exists so that decision is yours, with the number.",
      },
    ],
    legal: fact("warden", "legal", "2025-01-01"),
    childOk: false,
    mileOk: true,
    noCar: false,
    octoberOk: false,
    lengthM: fact("warden", 1900, "2026-06-03", "East shore to the dam and back."),
    notes: [
      {
        by: "Harri",
        date: "2025-08-12",
        text: "Skin swim in August. Beautiful and short. I had a flask and a dry layer in the bag, which was the actual swim kit.",
      },
    ],
  },
  {
    slug: "portnahaven-trough",
    name: "Portnahaven Trough",
    water: "tidal-pool",
    waterName: "Portnahaven Trough",
    county: "Argyll",
    nation: "Scotland",
    sheet: "RCH 44 / 02",
    chainageKm: 0,
    summary:
      "A concrete trough on an Atlantic village. The swell decides whether it is a pool or a pot.",
    access: fact("warden", "Village street to the sea wall. Slippery in any weather.", "2025-09-04"),
    parking: fact("warden", "Village, scarce. Bus from Bowmore on paper; check.", "2025-09-04"),
    depth: fact("warden", "1.5 m in a settled high water. In swell the depth is not the problem.", "2025-09-04"),
    current: fact("warden", "Swell surge. Not a tidal rip inside the trough; the danger is being lifted onto the wall.", "2025-09-04"),
    temperature: {
      spring: none(),
      summer: fact("sample", "13 °C", "2025-08-07"),
      autumn: fact("sample", "12 °C", "2025-09-04"),
      winter: none(),
    },
    quality: fact("sample", "excellent", "2025-08-07"),
    hazards: [
      {
        grade: "serious",
        title: "Atlantic swell",
        body: "On a calm day this is a cold, clear trough. On any swell it slams. There is no lifeguard and the next help is a long way.",
      },
    ],
    legal: fact("warden", "legal", "2025-01-01"),
    childOk: false,
    mileOk: false,
    noCar: false,
    octoberOk: false,
    lengthM: fact("warden", 25, "2025-09-04"),
    notes: [],
  },
  {
    slug: "abbey-mead",
    name: "Abbey Mead",
    water: "lake",
    waterName: "Abbey Mead",
    county: "Hampshire",
    nation: "England",
    sheet: "RCH 15 / 03",
    chainageKm: 0,
    summary:
      "A gravel-pit lake with a managed swim zone, a sample point, and a fence that people climb when the zone is closed.",
    access: fact("warden", "From the country-park gate. The swim zone is signed. The rest of the lake is not the swim.", "2026-07-20"),
    parking: fact("warden", "Country park, charged. Bus on the hour from Winchester.", "2026-07-20"),
    depth: fact("sample", "Zone marked to 1.5 m. Outside the rope the pit is 8 m.", "2026-06-02"),
    current: fact("warden", "None in the zone.", "2026-06-02"),
    temperature: {
      spring: fact("sample", "11 °C", "2026-04-21"),
      summer: fact("sample", "19 °C", "2026-08-06"),
      autumn: fact("sample", "14 °C", "2025-10-13"),
      winter: fact("warden", "Zone closed", "2026-01-01"),
    },
    quality: fact("sample", "excellent", "2026-08-06"),
    hazards: [
      {
        grade: "caution",
        title: "The rope is the information",
        body: "Inside the rope, this is as close as a gravel pit comes to a lido. Outside it, the old machinery and the deep water are still there. People climb the fence in the evening. That is a different entry, and it is not assessed as safe.",
      },
    ],
    legal: fact("sample", "designated", "2026-05-01"),
    childOk: true,
    mileOk: false,
    noCar: true,
    octoberOk: true,
    lengthM: fact("sample", 100, "2026-06-02"),
    notes: [
      {
        by: "Louise",
        date: "2026-08-06",
        text: "With a five-year-old, inside the rope, as intended. The notice about the rest of the lake is the most useful thing on the site.",
      },
    ],
  },
  {
    slug: "sunk-island",
    name: "Sunk Island",
    water: "coast",
    waterName: "Humber",
    county: "East Riding of Yorkshire",
    nation: "England",
    sheet: "RCH 07 / 28",
    chainageKm: 0,
    summary:
      "A name on the map and a 2020 note about ‘walking out’. The Humber is not a swimming sea. This record exists so the name does not look empty.",
    access: none(),
    parking: none(),
    depth: none(),
    current: none(),
    temperature: {
      spring: none(),
      summer: none(),
      autumn: none(),
      winter: none(),
    },
    quality: none(),
    hazards: [
      {
        grade: "unknown",
        title: "Estuary, unassessed",
        body: "The Humber has tides, shipping, and mud that is famous for a reason. We have no sounding, no current note, and no sample. A 2020 sentence about walking is not a swim report. Treat this as a place you have no information about.",
      },
    ],
    legal: fact("swimmer", "unclear", "2020-05-11"),
    childOk: null,
    mileOk: null,
    noCar: null,
    octoberOk: null,
    lengthM: none(),
    notes: [
      {
        by: "K.",
        date: "2020-05-11",
        text: "Walked out a long way at low water. Sky and mud. Did not swim. Putting it here because people ask.",
      },
    ],
  },
  {
    slug: "helwyn-passage",
    name: "Helwyn Passage",
    water: "coast",
    waterName: "Helwyn River mouth",
    county: "Cornwall",
    nation: "England",
    sheet: "RCH 31 / 27",
    chainageKm: 0.6,
    summary:
      "A ferry crossing that people treat as a swim on a neap. The ferry does not treat them as expected traffic.",
    access: fact("warden", "From either hard. Both are slipways, algae in season.", "2026-06-12"),
    parking: fact("warden", "Village car parks on both sides, small.", "2026-06-12"),
    depth: fact("warden", "Channel 4–8 m. The edges are mudbanks that vanish under the flood.", "2026-06-12"),
    current: fact(
      "warden",
      "The passage runs. Slack is short. A neap slack is the only window anyone local will name, and even then the ferry has priority.",
      "2026-06-12",
    ),
    temperature: {
      spring: fact("sample", "10 °C", "2026-04-19"),
      summer: fact("sample", "16 °C", "2026-08-03"),
      autumn: fact("sample", "14 °C", "2025-10-05"),
      winter: none(),
    },
    quality: fact("sample", "good", "2026-08-03"),
    hazards: [
      {
        grade: "serious",
        title: "Ferry and stream",
        body: "This is a crossing, not a pool. If you cannot hold a line in a current, you are in the ferry’s water. The mudbanks cut off retreat as the tide rises.",
      },
    ],
    legal: fact("warden", "tolerated", "2024-01-01"),
    childOk: false,
    mileOk: false,
    noCar: false,
    octoberOk: true,
    lengthM: fact("warden", 280, "2026-06-12", "Hard to hard, in a named slack only."),
    notes: [],
  },
  {
    slug: "camel-narrows",
    name: "Camel Narrows",
    water: "river",
    waterName: "River Camel",
    county: "Cornwall",
    nation: "England",
    sheet: "RCH 31 / 31",
    chainageKm: 9.8,
    summary:
      "Where the river stands on its edge. A serious current in a place people picnic.",
    access: fact("warden", "Camel trail, then a desire path down. The trail is for bikes; look behind you.", "2026-07-04"),
    parking: fact("warden", "Trail car parks. Summer is a queue.", "2026-07-04"),
    depth: fact("warden", "Narrow and deep: 2–3 m in the thread.", "2025-07-15"),
    current: fact(
      "warden",
      "Fast in the thread after any rain, and on the ebb when the tide still reaches this far. The picnic beach is an eddy. The eddy fails.",
      "2026-07-04",
    ),
    temperature: {
      spring: fact("sample", "10 °C", "2026-04-13"),
      summer: fact("sample", "17 °C", "2025-07-15"),
      autumn: fact("sample", "13 °C", "2025-10-09"),
      winter: none(),
    },
    quality: fact("sample", "sufficient", "2025-07-15"),
    qualityAfterRain: "Agricultural and a small overflow at the village. After rain, assume worse than the last sample.",
    hazards: [
      {
        grade: "serious",
        title: "Eddy that fails",
        body: "Children sit in the eddy. Adults swim the thread for a photograph. The eddy collapses when a pulse of water comes down, which can be a boat wake or a cloud on Bodmin.",
      },
    ],
    legal: fact("warden", "tolerated", "2025-01-01"),
    childOk: false,
    mileOk: false,
    noCar: false,
    octoberOk: false,
    lengthM: fact("warden", 60, "2025-07-15"),
    notes: [],
  },
  {
    slug: "pye-strand",
    name: "Pye Strand",
    water: "coast",
    waterName: "North Sea",
    county: "Suffolk",
    nation: "England",
    sheet: "RCH 04 / 17",
    chainageKm: 0,
    summary:
      "A name, a grid, and a note from a hot week in 2019. The North Sea did not write back.",
    access: none(),
    parking: none(),
    depth: none(),
    current: none(),
    temperature: {
      spring: none(),
      summer: none(),
      autumn: none(),
      winter: none(),
    },
    quality: none(),
    hazards: [
      {
        grade: "unknown",
        title: "No assessment",
        body: "Suffolk beaches have rips, groynes, and a steepening shore. None of that has been written down for this strand. The 2019 note is a holiday sentence. It is printed below as a note, not as a condition report.",
      },
    ],
    legal: none(),
    childOk: null,
    mileOk: null,
    noCar: null,
    octoberOk: null,
    lengthM: none(),
    notes: [
      {
        by: "Sam",
        date: "2019-07-24",
        text: "Hot week. Went in off the shingle. Cold and clear. No one else. Good lunch in the village.",
      },
    ],
  },
];
