/**
 * The artifact is the same integrator the bench runs: spring, magnet,
 * per-target rules. Paste CSS + JS. No framework. Text keeps the caret.
 */

import type { Recipe, Target } from "./system";

export function fileStem(recipe: Recipe): string {
  return `index-${recipe.id}`;
}

function recipeLiteral(recipe: Recipe): string {
  const rules = (Object.keys(recipe.rules) as Target[])
    .map((k) => {
      const r = recipe.rules[k];
      return `    ${k}: { shape: "${r.shape}", size: ${r.size}, magnet: ${r.magnet} }`;
    })
    .join(",\n");
  return `{
  id: ${JSON.stringify(recipe.id)},
  name: ${JSON.stringify(recipe.name)},
  ink: ${JSON.stringify(recipe.ink)},
  mass: ${Number(recipe.mass.toFixed(4))},
  damping: ${Number(recipe.damping.toFixed(4))},
  magnetRadius: ${Number(recipe.magnetRadius.toFixed(2))},
  magnetPull: ${Number(recipe.magnetPull.toFixed(4))},
  aim: ${recipe.aim},
  rules: {
${rules}
  }
}`;
}

export function emitCss(recipe: Recipe): string {
  const stem = fileStem(recipe);
  return `/**
 * Index — ${recipe.name}
 * Pointer grammar. Applied only after attach() adds .${stem}-on,
 * so a missing script never leaves the page without a cursor.
 *
 * Text fields, selectable copy, and [data-ptr="text"] keep cursor: text
 * and the native caret. Keyboard is not captured.
 */

html.${stem}-on,
html.${stem}-on * {
  cursor: none !important;
}

html.${stem}-on.${stem}-text,
html.${stem}-on.${stem}-text *,
html.${stem}-on input:not([type="button"]):not([type="submit"]):not([type="reset"]):not([type="checkbox"]):not([type="radio"]):not([type="file"]),
html.${stem}-on textarea,
html.${stem}-on select,
html.${stem}-on [contenteditable="true"],
html.${stem}-on [data-ptr="text"] {
  cursor: text !important;
}

.${stem}-mark {
  position: fixed;
  left: 0;
  top: 0;
  width: 72px;
  height: 72px;
  margin: -36px 0 0 -36px;
  pointer-events: none;
  z-index: 2147483646;
  overflow: visible;
  color: ${recipe.ink};
}

.${stem}-mark[data-haze="true"] {
  filter: blur(11px);
}

@media (pointer: coarse) {
  html.${stem}-on,
  html.${stem}-on * {
    cursor: auto !important;
  }
  html.${stem}-on.${stem}-text,
  html.${stem}-on.${stem}-text * {
    cursor: text !important;
  }
}

@media (prefers-reduced-motion: reduce) {
  .${stem}-mark {
    transition: none;
  }
}
`;
}

export function emitJs(recipe: Recipe): string {
  const stem = fileStem(recipe);
  const ink = recipe.ink;
  return `/**
 * Index — ${recipe.name}
 * Generated by Index. Same spring, same rules as the bench.
 *
 * <link rel="stylesheet" href="./${stem}.css">
 * <script type="module">
 *   import { attach } from "./${stem}.js";
 *   attach();
 * </script>
 *
 * Optional: data-ptr="link|button|text|drag|wait|disabled" on a node.
 * Heuristics cover a, button, input, textarea, [draggable], [disabled].
 * Over text the mark hides and the caret stays. Keyboard is untouched.
 */

export const recipe = ${recipeLiteral(recipe)};

function markInner(shape, size, filled) {
  const s = Math.max(4, size);
  const sw = 1.2;
  const fill = filled ? "currentColor" : "none";
  if (shape === "native") return "";
  if (shape === "dot") return '<circle r="' + (s / 2) + '" fill="currentColor"/>';
  if (shape === "ring") return '<circle r="' + (s / 2) + '" fill="' + fill + '" stroke="currentColor" stroke-width="' + sw + '"/>';
  if (shape === "cross") return '<path d="M' + (-s / 2) + ' 0h' + s + 'M0 ' + (-s / 2) + 'v' + s + '" fill="none" stroke="currentColor" stroke-width="' + sw + '"/>';
  if (shape === "bar") return '<path d="M' + (-s / 2) + ' 0h' + s + '" fill="none" stroke="currentColor" stroke-width="' + sw + '"/>';
  if (shape === "arrow") return '<path d="M' + (-s * 0.28) + ' ' + (-s * 0.42) + ' L' + (s * 0.38) + ' 0 L' + (-s * 0.28) + ' ' + (s * 0.42) + ' Z" fill="' + fill + '" stroke="currentColor" stroke-width="' + sw + '" stroke-linejoin="miter"/>';
  if (shape === "corners") {
    const a = s / 2, k = s * 0.32;
    return (
      '<path d="M' + (-a) + ' ' + (-a + k) + 'V' + (-a) + 'h' + k + '" fill="none" stroke="currentColor" stroke-width="' + sw + '"/>' +
      '<path d="M' + (a - k) + ' ' + (-a) + 'H' + a + 'v' + k + '" fill="none" stroke="currentColor" stroke-width="' + sw + '"/>' +
      '<path d="M' + a + ' ' + (a - k) + 'V' + a + 'h' + (-k) + '" fill="none" stroke="currentColor" stroke-width="' + sw + '"/>' +
      '<path d="M' + (-a + k) + ' ' + a + 'H' + (-a) + 'v' + (-k) + '" fill="none" stroke="currentColor" stroke-width="' + sw + '"/>'
    );
  }
  if (shape === "square") return '<rect x="' + (-s / 2) + '" y="' + (-s / 2) + '" width="' + s + '" height="' + s + '" fill="' + fill + '" stroke="currentColor" stroke-width="' + sw + '"/>';
  if (shape === "sight") {
    return (
      '<circle r="' + (s / 2) + '" fill="none" stroke="currentColor" stroke-width="' + sw + '"/>' +
      '<circle r="' + (s / 5.5) + '" fill="' + fill + '" stroke="currentColor" stroke-width="' + sw + '"/>' +
      '<path d="M' + (-s * 0.72) + ' 0h' + (s * 0.2) + 'M' + (s * 0.52) + ' 0h' + (s * 0.2) + 'M0 ' + (-s * 0.72) + 'v' + (s * 0.2) + 'M0 ' + (s * 0.52) + 'v' + (s * 0.2) + '" fill="none" stroke="currentColor" stroke-width="' + sw + '"/>'
    );
  }
  if (shape === "haze") return '<circle r="' + (s / 2) + '" fill="currentColor" opacity="0.42"/>';
  return "";
}

function selectable(node) {
  const t = node.tagName;
  return t === "P" || t === "H1" || t === "H2" || t === "H3" || t === "H4" || t === "LI" || t === "BLOCKQUOTE" || t === "LABEL" || t === "DD" || t === "DT";
}

function detect(el, busy) {
  if (busy) return "wait";
  let node = el;
  while (node && node !== document.documentElement) {
    if (node instanceof HTMLElement) {
      const ptr = node.getAttribute("data-ptr");
      if (ptr === "wait") return "wait";
      if (ptr === "disabled") return "disabled";
      if (ptr === "text") return "text";
      if (ptr === "drag") return "drag";
      if (ptr === "button") return "button";
      if (ptr === "link") return "link";
      if (ptr === "rest") return "rest";
      if (node.getAttribute("aria-disabled") === "true") return "disabled";
      if ((node instanceof HTMLButtonElement || node instanceof HTMLInputElement || node instanceof HTMLTextAreaElement || node instanceof HTMLSelectElement) && node.disabled) return "disabled";
      if (node instanceof HTMLInputElement && ["text", "search", "email", "url", "tel", "password", "number", "date", ""].indexOf(node.type) >= 0) return "text";
      if (node instanceof HTMLTextAreaElement || node instanceof HTMLSelectElement) return "text";
      if (node.getAttribute("contenteditable") === "true") return "text";
      if (node.getAttribute("role") === "link") return "link";
      if (node instanceof HTMLAnchorElement && node.href) return "link";
      if (node.getAttribute("role") === "button" || node instanceof HTMLButtonElement) return "button";
      if (node instanceof HTMLInputElement && ["button", "submit", "reset"].indexOf(node.type) >= 0) return "button";
      if (node.getAttribute("draggable") === "true") return "drag";
      if (selectable(node)) return "text";
    }
    node = node.parentElement;
  }
  return "rest";
}

function magnet(el, target, mx, my) {
  const rule = recipe.rules[target];
  if (!rule || !rule.magnet || recipe.magnetRadius <= 0 || recipe.magnetPull <= 0 || !el) {
    return { x: mx, y: my };
  }
  const box = el.getBoundingClientRect();
  const cx = box.left + box.width / 2;
  const cy = box.top + box.height / 2;
  const dx = cx - mx;
  const dy = cy - my;
  const d = Math.hypot(dx, dy);
  if (d > recipe.magnetRadius || d < 0.001) return { x: mx, y: my };
  const t = (1 - d / recipe.magnetRadius) * recipe.magnetPull;
  return { x: mx + dx * t, y: my + dy * t };
}

export function attach(options) {
  options = options || {};
  const root = options.root || document.documentElement;
  const reducedMq = window.matchMedia("(prefers-reduced-motion: reduce)");
  const coarseMq = window.matchMedia("(pointer: coarse)");
  let busy = !!options.busy;
  let pressed = false;
  let mx = window.innerWidth * 0.5;
  let my = window.innerHeight * 0.35;
  let over = null;
  let target = "rest";
  let shown = false;
  const body = { x: mx, y: my, vx: 0, vy: 0 };
  let angle = 0;
  let spin = 0;
  let acc = 0;
  let last = performance.now();
  let raf = 0;
  const DT = 1 / 120;

  const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
  svg.setAttribute("class", "${stem}-mark");
  svg.setAttribute("viewBox", "-36 -36 72 72");
  svg.setAttribute("aria-hidden", "true");
  svg.setAttribute("data-index-mark", "true");
  svg.style.color = "${ink}";
  let seeded = false;

  function fine() {
    return !coarseMq.matches;
  }

  function applyRoot() {
    if (fine()) root.classList.add("${stem}-on");
    else root.classList.remove("${stem}-on");
    if (target === "text") root.classList.add("${stem}-text");
    else root.classList.remove("${stem}-text");
  }

  function paint() {
    const rule = recipe.rules[target] || recipe.rules.rest;
    const hide = !shown || rule.shape === "native" || target === "text";
    svg.style.display = hide ? "none" : "block";
    if (hide) return;
    const filled = pressed && target !== "text" && target !== "disabled";
    svg.innerHTML = markInner(rule.shape, rule.size, filled);
    svg.setAttribute("data-haze", rule.shape === "haze" ? "true" : "false");
    const scale = filled ? 0.62 : 1;
    const rot = target === "wait" && !reducedMq.matches ? spin : recipe.aim ? angle : 0;
    svg.style.transform = "translate(" + body.x + "px," + body.y + "px) rotate(" + rot + "deg) scale(" + scale + ")";
  }

  function step(dt) {
    const reduced = reducedMq.matches;
    const pull = magnet(over, target, mx, my);
    if (reduced || !isFinite(body.x) || !isFinite(body.vx)) {
      body.x = pull.x;
      body.y = pull.y;
      body.vx = 0;
      body.vy = 0;
      return;
    }
    const jump = Math.hypot(pull.x - body.x, pull.y - body.y);
    if (jump > 280 && Math.hypot(body.vx, body.vy) < 90) {
      body.x = pull.x; body.y = pull.y; body.vx = 0; body.vy = 0;
      return;
    }
    const u = Math.min(1, Math.max(0, (recipe.mass - 0.06) / 0.66));
    const omega = 22 - u * 14;
    const zeta = Math.min(1.35, Math.max(0.7, 0.7 + recipe.damping * 0.45));
    const ax = omega * omega * (pull.x - body.x) - 2 * zeta * omega * body.vx;
    const ay = omega * omega * (pull.y - body.y) - 2 * zeta * omega * body.vy;
    body.vx += ax * dt;
    body.vy += ay * dt;
    const spd = Math.hypot(body.vx, body.vy);
    if (spd > 2800) {
      body.vx *= 2800 / spd;
      body.vy *= 2800 / spd;
    }
    body.x += body.vx * dt;
    body.y += body.vy * dt;
    if (recipe.aim && spd > 40) angle = (Math.atan2(body.vy, body.vx) * 180) / Math.PI;
    if (target === "wait" && !reduced) spin += dt * 140;
    else if (target !== "wait") spin = 0;
  }

  function frame(now) {
    const dt = Math.min(0.048, (now - last) / 1000);
    last = now;
    acc += dt;
    while (acc >= DT) {
      step(DT);
      acc -= DT;
    }
    paint();
    raf = requestAnimationFrame(frame);
  }

  function read(e) {
    mx = e.clientX;
    my = e.clientY;
    shown = true;
    if (!seeded) {
      seeded = true;
      body.x = mx;
      body.y = my;
      body.vx = 0;
      body.vy = 0;
    }
    const node = document.elementFromPoint(mx, my);
    over = node;
    target = detect(node, busy);
    applyRoot();
  }

  function down(e) {
    if (e.pointerType === "mouse" || e.pointerType === "pen") pressed = true;
    read(e);
  }

  function up() {
    pressed = false;
  }

  function leave() {
    shown = false;
    target = "rest";
    applyRoot();
    paint();
  }

  root.appendChild(svg);
  applyRoot();
  window.addEventListener("pointermove", read, { passive: true });
  window.addEventListener("pointerdown", down, { passive: true });
  window.addEventListener("pointerup", up, { passive: true });
  window.addEventListener("pointercancel", up, { passive: true });
  document.addEventListener("mouseleave", leave);
  raf = requestAnimationFrame(frame);

  return {
    get target() { return target; },
    setBusy(on) { busy = !!on; },
    destroy() {
      cancelAnimationFrame(raf);
      window.removeEventListener("pointermove", read);
      window.removeEventListener("pointerdown", down);
      window.removeEventListener("pointerup", up);
      window.removeEventListener("pointercancel", up);
      document.removeEventListener("mouseleave", leave);
      root.classList.remove("${stem}-on", "${stem}-text");
      svg.remove();
    },
  };
}
`;
}

export function emitPreview(recipe: Recipe): string {
  const css = emitCss(recipe).split("\n").slice(0, 12).join("\n");
  const js = emitJs(recipe).split("\n").slice(0, 16).join("\n");
  return `${css}\n\n/* — ${fileStem(recipe)}.js — */\n${js}\n`;
}
